### ISSUE TITLE
Numpy: FATAL  Error, failed to find path @rpath/libffi.7.dylib (pygame package installation)

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1860]
Environment:
MACOS Monterey
Python:Anaconda 3.7.12
Nuitka:1.2rc6

How did you install Nuitka and Python
pip

The specific PyPI names and versions
numpy  1.21.6

Provide in your issue the Nuitka options used
sudo python -m nuitka --run --standalone  --enable-plugin=numpy,pyside2 --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site main.py; date

Error during nuitka standalone compilation:
Nuitka-Plugins:INFO: numpy: Found 11 files DLLs from numpy installation.
FATAL: Error, failed to find path @rpath/libffi.7.dylib (resolved DLL to /Users/emre/opt/anaconda3/envs/object_detection/lib/python3.7/site-packages/libffi.7.dylib) for /Users/emre/opt/anaconda3/envs/object_detection/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so, please report the bug.

**Comment by kayhayen** [comment]
This seems to be missing a script to reproduce, and maybe a conda environment file. Also please always use --version output of Nuitka instead of writing up a subset of its output.

**Comment by emre84** [comment]
Hi Kay,

Oppss. Sorry.

**Environment:**
[environment.txt](https://github.com/Nuitka/Nuitka/files/9882756/environment.txt)

**Script:** (pygame 2.1.2)
import pygame

**Version:**
(object_detection) emres-Air:tests emre$ python -m nuitka --version
1.2rc6
Commercial: None
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
Flavor: Anaconda Python
Executable: /Users/emre/opt/anaconda3/envs/object_detection/bin/python3
OS: Darwin
Arch: x86_64

**Comment by kayhayen** [comment]
I didn't manage to import the environment file, Anaconda gives me a crash report trying that, something with the json being wrong, but I am pretty sure it ought to be OK.

I didn't find the 3.7.12, but only 3.7.13 and I didn't find pygame, not even on conda forge, so I pip installed it, and it just works.

I guess, thanks to the fluent nature of Anaconda, your environment is not reproducible. Can you update your conda environment to existing versions?

**Comment by emre84** [comment]
Hi Kay, 

I tried to update my Anaconda to current version as you mentioned above, I got an json either. I guess there were something wrong with my Anaconda installation from the beginning but anyway I will keep going to work with CPython(with the reason that #1841 is solved now.) So you can close this issue. Thanks a lot.

**Comment by kayhayen** [comment]
Sorry, this didn't resolve. I believe there is some sort of bug in Nuitka still for a corner case, but this is not how we find it. Thanks for reporting, this can happen.
