### ISSUE TITLE
Onefile: Killing the bootstrapped process twice can cause left over forked process that lock parts of the temp files

### ISSUE THREAD

**Issue by Pragmatism0220** [Nuitka/Nuitka#2000]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```shell
1.3.5
Commercial: None
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\miniconda3\envs\mortal\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: E:\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.exe (cl 14.3).
```

* How did you install Nuitka and Python

 pip in miniconda

* Provide in your issue the Nuitka options used

```shell
nuitka --standalone --onefile --noinclude-unittest-mode=nofollow --remove-output main.py
```

OK. The problem is as described in the title. There are **two** main situations:
1. Click "x" in the upper right corner of the cmd console to close the program. At this time, the problem will be triggered stably and the onefile-folder will not be deleted automatically. The simplest **test code** is `while True: pass`, and use Nuitka. I think it can be achieved by capturing signals. For example, the Windows operating system provides [SetConsoleCtrlHandler]( https://learn.microsoft.com/en-us/windows/console/setconsolectrlhandler)；
2. When "ctrl-c" terminates the program: when use `import torch`, it will not be automatically deleted. Here is a sample.
```py
import torch  # Just for test. It's not actually used here.


if __name__ == '__main__':
    print('Ready!')
    try:
        while True:
            pass
    except:
        print('Exception!')

```
![image](https://user-images.githubusercontent.com/55100969/212528625-7f09842d-db20-419e-9c12-0ccbe1b25918.png)

By the way, an irrelevant question: the `torch` module makes the program very large, and the packaging and decompression are also very slow. Is there any good way?

Hope to seek some suggestions.

**Comment by Pragmatism0220** [comment]
I forgot to mention that the program I created is a pure **console program** without GUI. My computer operating system is win10.

**Comment by kayhayen** [comment]
I think the deletion should happen after a reboot. This is definitely not optimal. Generally it also seems, we wait for the child to exit, before ordering that. This should have a timeout. What might happen in your case, is that the CTRL-C gets ignored by the child process, or it somehow can be considered not exited. In that case, the onefile binary may also hang forever.

**Comment by kayhayen** [comment]
@Pragmatism0220 ok, thanks for pointing that out, I will check it out. If there is some locking going on, I believe these files should be scheduled for deletion at reboot. For now, I found bugs in the CTRL-C interaction and fixed them. I invite you to try out factory branch:

It is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

It may however only hide the issue, The double CTRL-C that I removed may well be preventing cleanup from the client program, but it's cooperation ought to be unnecessary of course, so not sure what this is. Also locks may still be held at  the time exit is reported.

**Comment by Pragmatism0220** [comment]
OK. This development version has a new bug. When it tries to use the "-- include-data-files" option, it will report an error:
**command**：`nuitka --standalone --onefile --include-data-files=./wrapper/protoc.exe=wrapper/ --remove-out main.py`
**error**:
```
Nuitka-Options:INFO: Used command line options: --standalone --onefile --include-data-files=./wrapper/protoc.exe=wrapper/ --remove-out main.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.4rc9' on Python '3.10' commercial grade 'not installed'.
Traceback (most recent call last):
  File "D:\miniconda3\envs\cmortal\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "D:\miniconda3\envs\cmortal\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "D:\miniconda3\envs\cmortal\lib\site-packages\nuitka\MainControl.py", line 934, in main
    addIncludedDataFilesFromFileOptions()
  File "D:\miniconda3\envs\cmortal\lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 342, in addIncludedDataFilesFromFileOptions
    for included_datafile in _addIncludedDataFilesFromFileOptions():
  File "D:\miniconda3\envs\cmortal\lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 307, in _addIncludedDataFilesFromFileOptions
    if containsPathElements(rel_path, default_ignored_dirs):
  File "D:\miniconda3\envs\cmortal\lib\site-packages\nuitka\utils\FileOperations.py", line 1058, in containsPathElements
    elements = tuple(os.path.normcase(elements))
  File "D:\miniconda3\envs\cmortal\lib\ntpath.py", line 56, in normcase
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not tuple
```
------
And unfortunately, the development version still hasn't solved this problem. The onefile folder is still not removed. And because the torch is large, it will take up a very large space of the temporary folder during multiple runs.
![image](https://user-images.githubusercontent.com/55100969/212844260-8f9311ce-b3a6-4dc3-a0c8-5883f0774045.png)
![image](https://user-images.githubusercontent.com/55100969/212844322-b7011980-ceb4-4bd4-b09e-b85ab5fa4987.png)

**Comment by kayhayen** [comment]
Thanks, I fixed the factory version, but I will have to look into how this can happen myself. Thankfully you have provided a reproducer, so hopefully it will be more obvious. I kind of wanted to address the obvious flaw that I discovered from looking at it, but now I am very puzzled as to how this can happen naturally. If you were to retry, that would help. But I take it, this is only a subset of the files, right, so deleting probably indeed failed due to locks.

This was probably `protoc.exe`. Nuitka will become resistant against including binaries as data files btw, since they usually need treatment to be portable.

So theorizing about what's going on, you probably have a child process forked, and do not clean it up in case of CTRL-C. I do not think Python would do that, does it? Which is a valid error to make as a programmer. You probably should have an `atexit` or a try finally block, or something like that. This is what your grace time is for. The double CTRL-C may well prevent any such measure of yours from actually being executed. Then factory will already be better for you.

And if indeed that is what is going on, and this child process then locks data files or DLLs, they cannot be removed, which would explain things. Not sure of course, a minimal reproducer of this will always be good I guess.

So 2 things to improve here. During cleanup, on Windows, we should delete, and if that doesn't work, wait a small time and retry afterwards, there is no harm in this, avoiding races. The virus scanners and what not tools can prevent successful deletion of everything, e.g. they may not have released locks on binaries that were started yet.

Since the launched process may not be connected to the terminal, it will not always get the CTRL-C event. You may in fact even strive for it to be detached. I frequently do so, removing standard input, just to avoid tools messing with it. So, what we should be doing, is to also kill all children processes on Windows.

With that, the shutdown should be much more reliable. The question is of course, what happens if a forked child is *supposed* to survive the onefile binary. Then we cannot kill it. So maybe it's not an option to do that?

**Comment by Pragmatism0220** [comment]
Thank you very much for your detailed reply!
In fact, the program that caused this problem does not contain child processes (at least not in the code I wrote, unless some packages are implicitly called). `protoc.exe` is included in the torch. I'm afraid it is necessary, and I can't help it.
There is no doubt that my program contains a `try-except` block for exception processing and log handling. At the same time, I called the `SetConsoleCtrlHandler` interface to perform exit processing, which should play a similar role as `atexit`.
Perhaps timeout retry is a good way to solve this problem? I tried to monitor the changes in the process, but didn't find any obvious problems. But at least one thing I'm sure of: after I press CTRL-C, the process group of exe is indeed closed.
I also consider starting a detach subprocess in my exit processing module to clean up temporary files. But before that, I will try the factory version again, hoping to gain something. :-)

------

> With that, the shutdown should be much more reliable. The question is of course, what happens if a forked child is supposed to survive the onefile binary. Then we cannot kill it. So maybe it's not an option to do that?

I think this situation is very bad. It is not a good habit of programming. As a programmer, we should avoid this situation and correctly handle these processes in the code, such as setting them as daemons. Otherwise, when onefile exe is closed, resources will not be released, resulting in many unexpected bugs. In this case, I think this is not a problem that Nuitka should deal with, but a problem that programmers themselves need to deal with.

**Comment by kayhayen** [comment]
With two CTRL-C in a row (which is the bug present on current stable Nuitka and fixed on factory now), it's quite possible that your CTRL-C handler itself is interrupted, causing the program to exit without doing the necessary cleanup.

If a child uses the onefile contents and shall survive the execution, it would have not use the temporary files mode, and use the cached. Check the user manual if you want for the difference. Unfortunately, currently it doesn't save as much time compared to temp files, since at startup it still decompresses and validates the contents to match, but that will change. It's on the roadmap for future releases. But I believe now I have solved your current issue. The double CTRL-C is not happening anymore, so if your cleanup code is any good, then the perfect cleanup will already happen, even if it requires your cooperation, it now will not be disturbed.

**Comment by Pragmatism0220** [comment]
Unfortunately, in my example, it is not caused by CTRL-C twice. Using CTRL-C only once will still cause problems, even the factory version will not work.
The example of reproduce is still the following code:
```py
import torch  # Just for test. It's not actually used here.


if __name__ == '__main__':
    print('Ready!')
    try:
        while True:
            pass
    except:
        print('Exception!')
```
Press CTRL-C only once, but the onefile folder is still not deleted. Maybe Nuitka might send the signal twice when handling, but even the repaired version still doesn't work.
![image](https://user-images.githubusercontent.com/55100969/212975716-0552c62e-defa-48b9-8d3b-53d5bf319c9e.png)
I have managed to "mitigate" this bug in my way. Here is my solution: I delayed trying to delete the temporary folder after catching the close signal.
```py
import torch
import os
import win32api


def clear_nuitka_onefile_temp_dir():
    if 'NUITKA_ONEFILE_PARENT' in os.environ:
        from tempfile import gettempdir
        from subprocess import Popen, DEVNULL, CREATE_NEW_PROCESS_GROUP, CREATE_NO_WINDOW

        nuitka_onefile_temp_dir = 'onefile_%d_*' % int(os.environ['NUITKA_ONEFILE_PARENT'])
        Popen(f'timeout /t 8 /nobreak && pushd "{gettempdir()}" && (for /f "delims=" %i in '
              f'(\'dir {nuitka_onefile_temp_dir} /ad /b\') do rmdir /s /q %i) & '
              f'if exist comtypes_cache (rmdir /s /q comtypes_cache)', shell=True, stdout=DEVNULL, stderr=DEVNULL,
              creationflags=CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW)


def console_ctrl_handler(event):
    CTRL_C_EVENT = 0
    CTRL_BREAK_EVENT = 1
    CTRL_CLOSE_EVENT = 2
    CTRL_LOGOFF_EVENT = 5
    CTRL_SHUTDOWN_EVENT = 6

    CTRL_EVENT = {CTRL_C_EVENT, CTRL_BREAK_EVENT, CTRL_CLOSE_EVENT, CTRL_LOGOFF_EVENT, CTRL_SHUTDOWN_EVENT}

    if event in CTRL_EVENT:
        if event != CTRL_C_EVENT and event != CTRL_BREAK_EVENT:
            clear_nuitka_onefile_temp_dir()
        
    return False  # chain to next handler


if __name__ == '__main__':
    print('Ready!')
    win32api.SetConsoleCtrlHandler(console_ctrl_handler, True)
    try:
        while True:
            pass
    except:
        print('Exception!')
        clear_nuitka_onefile_temp_dir()
```

**Comment by kayhayen** [comment]
You are not getting what I am saying. You send CTRL-C, and then onefile binary did *again*. So the process was receiving it twice, making it so that your exception handler will very likely have a chance to also be interrupted. I never said you did that.

This is now on develop branch and will be in 1.4 release. The hard kill was added for Windows and Linux/macOS after a timeout, and there is hope this will make it go away for as long as no locks through leave over processes are caused by you.

**Comment by Pragmatism0220** [comment]
I'm sorry to bother you, but I have fully understood what you mean now, thanks! In short, after I press ctrl-c once, the program actually receives two ctrl-c signals: one from me and the other from onefile binary. The second ctrl-c is equivalent to a process termination signal, which makes the exe file behave abnormally.
The current processing, if I understand correctly, does something like signal masking for the second ctrl-c and adds a timeout, giving me a chance to do my own ctrl-c processing during this time.
In fact, I did construct an example that actually shows your change. Here is it:
```py
import torch


if __name__ == '__main__':
    print('Ready!')
    try:
        while True:
            pass
    except:
        print('Exception!')
        while True:  # Here
            pass

```
In the stable version of version 1.3, the above code will directly capture the second ctrl-c signal in the second while loop; In the development version 1.4, the second while loop will be executed normally for a period of time, and then it will be forcibly terminated after timeout. **Thank you very much for your great work!**

------

But now my problem is that I really **need to use the torch package** in my project, and I don't want to guide my users to install additional torch - in other words, I need to package the torch package into onefile, and the final file is acceptable if it is slightly larger.
But now the problem is that even with the 1.4 development version, **pressing ctrl-c will still not be able to clear the temporary files brought by torch**. I have clarified this point in my previous comments. I noticed that the torch module involves multiprocessing, which may be the cause of the deletion failure. Can't we really solve this problem?

**Comment by kayhayen** [comment]
Yes, the second signal is now a hard kill. You pick the time after which it is done with an option, defaulting to 5 seconds.

I honestly didn't look yet, if including torch alone does the bad thing. The multiprocessing should not play a role, and I think would behave well. If torch launches a process and doesn't end it, that's bad any your task to solve that. If I can see it with a mere import torch, I will try and fix it. But I never noticed any such process so far.

What I have a suspect could also be going on is that a Virus Scanner is preventing the deletion or something like that. Retrying to delete in some sort of loop might be necessary, or the registration of the deletion on reboot if all fails. There clearly is more robustness to be had there either way, even if there is also something specific to torch, it will be nice to better mitigate. I was thinking the Win32 function used does delete on reboot, but I am not so sure anymore, I didn't see it when I checked the docs recently.

But deleting the folder twice cannot be a mistake, or can it.

**Comment by Pragmatism0220** [comment]
During the test, I have shut down the computer's antivirus software and defender. I tried to throw an exception and found that Nuitka could delete the temporary file correctly(At this time, I do not press ctrl-c):
```py
import torch
import time


if __name__ == '__main__':
    print('Ready!')
    try:
        time.sleep(10)
        raise KeyboardInterrupt
    except:
        print('Exception!')

```
This makes me very confused. Does this mean that the hard kill signal brought by the second ctrl-c also killed the automatic deletion operation?

**Comment by kayhayen** [comment]
No, the deletion is done by the onefile binary. I think this means that an extra ball for the deletion will already work. Of course, your customers are going to have AV on as well. I never do, because checking my source and object files, I do not want to waste CPU on that, and wait in loops before an executable can be removed, etc. this is just a very ugly reality of Windows I guess.

The symptom can be cause by different things here. The forked off process not being stopped, or the AV keeping locks on files until it feels it's done with them.

**Comment by Pragmatism0220** [comment]
OK, thank you very much for your reply! I think I have understood Nuitka's way of working on this. Thank you again!

**Comment by kayhayen** [comment]
I actually managed myself to reproduce the CTRL-C leaving over files with torch sized bootstrapped process. On my machine that is without an AV. But with my latest factory code change, it now retries 20 times with 0.1s delay, and it never happens anymore. It feels like this might be a race between Windows closing down the executable, but not having released all the locks yet, or something like that. Also, I would have to speculate that the deletion aborts on first error, and doesn't resume with what is feasible to delete.

Anyway, seems this got a lot more robust now.

**Comment by Pragmatism0220** [comment]
Yes! I used the latest code for testing, and it performed perfectly! Thank you for your hard work!

**Comment by kayhayen** [comment]
This too now is on develop, and waiting for the 1.4 release.

**Comment by Pragmatism0220** [comment]
Hi, I'm sorry to bother you again, but believe me I didn't mean to :-(. But I have one more question: the same code that contains torch, after I use ctrl-c, or even after I terminate the process directly in the task manager, **still has to wait for a full 5s grace time** to exit the console window. Why? If the torch is not included, it can immediately respond and close the window.
![image](https://user-images.githubusercontent.com/55100969/213903696-a2cf22be-cb3b-4cb5-82b1-b1cde850f3b7.png)

**Comment by Pragmatism0220** [comment]
> It feels like this might be a race between Windows closing down the executable, but not having released all the locks yet, or something like that.
Is this also the reason for this phenomenon, so that `WaitForSingleObject` cannot receive the correct signal in Nuitka's judgment of the child process, resulting in hard killing after 5s-timeout?

**Comment by Pragmatism0220** [comment]
> It feels like this might be a race between Windows closing down the executable, but not having released all the locks yet, or something like that.
Is this also the reason for this phenomenon, so that `WaitForSingleObject` cannot receive the correct signal in Nuitka's judgment of the child process, resulting in hard killing after 5s-timeout?

**Comment by kayhayen** [comment]
This is part of the stable release 1.5 that I just made.
