### ISSUE TITLE
PandasUsing failing locally on openSUSE due to local additional packages

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#2013]
On `main` (will retry on `develop` soon)...

 I initially had two separate fatal errors which I could resolve by removing the packages concerned.

```
FATAL: Error, forbidden import of 'setuptools_scm' in module 'pyarrow' at '/usr/lib64/python3.10/site-packages/pyarrow/__init__.py:44' encountered.
```

```
+FATAL: Error, forbidden import of 'numba' in module 'pandas.core._numba.kernels.var_' at '/usr/lib64/python3.10/site-packages/pandas/core/_numba/kernels/var_.py:11' encountered.
```

With those out of the way, I get this very strange error

```
Consider output of standalone mode compiled program: PandasUsing.py
Comparing output of 'PandasUsing.py' using '/usr/bin/python3' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, --nowarn-mnemonic=debian-dist-packages, plugin_enable:no-qt, plugin_disable:pylint-warnings ...
--- /usr/bin/python3 (stdout)
+++ nuitka (stdout)

@@ -1 +1,3 @@

+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
 1.5.2
Updating CPython cache by force due to non-matching comparison results.
--- /usr/bin/python3 (stdout)
+++ nuitka (stdout)

@@ -1 +1,3 @@

+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
 1.5.2
Error, results differed (stdout).
...
```

Somehow the first line of this error message is being removed, rendering the error not very helpful to understand the problem.
https://github.com/Nuitka/Nuitka/blob/a7d12c7650ed5b26b6b214023d493ad54304f9f1/nuitka/plugins/standard/PySidePyQtPlugin.py#L1042
Fixing that error reporting is IMO the most important aspect of this, so then I can find out what else needs to be removed in order to be able to run the tests.

**Comment by kayhayen** [comment]
The issue with the trace is that it is using up multiple lines, while only the first one has the logger prefix, that makes it ignored it output comparison. The Qt plugins hate it to see both PySide6 and PyQt6 being imported, and will complain when they see that. Not really a warning, but an indication of a problem. Nuitka cannot include 2 Qts, and therefore leaves out one. In this case, the no-qt plugin hates any Qt usage without the user knowing that it is not fully compatible to ignore the output.

**Comment by kayhayen** [comment]
There is a fix on factory, that makes the message single line. For warnings, we do text wrap, but then I also visited all its usages, to decide if they are pre-formatted or not, this was one of them which is not. I will strive to do that for info as well well generally with 1.5 release cycle, for now the bug should be fixed for your CI. This will be in 1.4.1 as well.

**Comment by jayvdb** [comment]
If you are referring to https://github.com/Nuitka/Nuitka/commit/30596656c9f3301bcac4dd4e42d3cfeb080f626b , I cherry-picked that to develop, and re-ran the tests, but the unhelpful test failing message problem persists, only now I see multiple:
```
Consider output of standalone mode compiled program: PandasUsing.py
Comparing output of 'PandasUsing.py' using '/usr/bin/python3' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, --nowarn-mnemonic=debian-dist-packages, plugin_enable:no-qt ...
--- /usr/bin/python3 (stdout)
+++ nuitka (stdout)

@@ -1 +1,7 @@

+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
 1.5.2
Updating CPython cache by force due to non-matching comparison results.
--- /usr/bin/python3 (stdout)
+++ nuitka (stdout)

@@ -1 +1,7 @@

+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
+its use. As a result an "ImportError" might be given at run time. Uninstall
+it for full compatible behavior with the uncompiled code to debug it.
 1.5.2
Error, results differed (stdout).
Listing of dist folder 'PandasUsing.dist':
...
```

I dont understand why the pandas test cares about qt at all.  The qt libraries should be ignored by `PandasUsing`.
So, I removed the `PandasUsing` `no-qt` entry in `tests/standalone/run_all.py`, and re-ran, and I get a bizare "non-matching" when there are indeed no differences in the output.

```
Consider output of standalone mode compiled program: PandasUsing.py
Comparing output of 'PandasUsing.py' using '/usr/bin/python3' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing, --nowarn-mnemonic=debian-dist-packages ...
--- /usr/bin/python3 (stderr)
+++ nuitka (stderr)

@@ -0,0 +1,2 @@

+Nuitka-Plugins:WARNING: Use '--enable-plugin=pyside6' for: Standalone mode support and Qt plugins.
+Nuitka-Plugins:WARNING: Use '--enable-plugin=pyqt5' for: Inclusion of Qt plugins.
Updating CPython cache by force due to non-matching comparison results.
--- /usr/bin/python3 (stderr)
+++ nuitka (stderr)

@@ -0,0 +1,2 @@

+Nuitka-Plugins:WARNING: Use '--enable-plugin=pyside6' for: Standalone mode support and Qt plugins.
+Nuitka-Plugins:WARNING: Use '--enable-plugin=pyqt5' for: Inclusion of Qt plugins.
Error, results differed (stderr).
Listing of dist folder 'PandasUsing.dist':
...
```

So then I add `ignore_warnings`, and woot!, the test passes.

**Comment by kayhayen** [comment]
I added the use of no-qt plugin, because it actually includes Qt bindings, and actually several of them potentially, which just wastes compile time. Please just use 1.4.1 once it's out, and it will be good. It's also hard to predict which Qt binding to use, and then of course, the test is not exercising it anyway.

**Comment by kayhayen** [comment]
This should be solved a long time ago, forgot to close it.
