### ISSUE TITLE
Standalone: abc module not has "__file__" after build

### ISSUE THREAD

**Issue by wszgrcy** [Nuitka/Nuitka#2315]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
```
1.7.2
Commercial: None
Python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Flavor: Debian Python
Executable: /home/chen/my-project/text-generation-python-client/no-dep/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).
```

* How did you install Nuitka and Python

`pip install`
torch package is `pip install torch -t lib` after build success
I build sucess and run main.bin,and find error as follow
Then I trace the code and find `abc` module is `frozen` and not has `__file__` property

```
/home/chen/my-project/text-generation-python-client/out/main.dist/lib/peft/tuners/lora.py:240: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(
trainable params: 589824 || all params: 102658560 || trainable%: 0.5745492631106456
/home/chen/my-project/text-generation-python-client/out/main.dist/lib/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Exception in thread Thread-4 (_handle_eio_message):
Traceback (most recent call last):
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/threading.py", line 1016, in _bootstrap_inner
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/threading.py", line 953, in run
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/socketio/client.py", line 705, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/socketio/client.py", line 581, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/socketio/client.py", line 629, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/main.py", line 84, in train
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lora/train_lora.py", line 18, in <lambda>
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lora/train.py", line 71, in train
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/accelerate/utils/memory.py", line 132, in decorator
    return function(batch_size, *args, **kwargs)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/transformers/trainer.py", line 1728, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/transformers/trainer.py", line 1067, in create_optimizer_and_scheduler
    self.create_optimizer()
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/transformers/trainer.py", line 1111, in create_optimizer
    self.optimizer = optimizer_cls(optimizer_grouped_parameters, **optimizer_kwargs)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/transformers/optimization.py", line 427, in __init__
    super().__init__(params, defaults)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/optim/optimizer.py", line 218, in __init__
    self.add_param_group(param_group)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_compile.py", line 22, in inner
    import torch._dynamo
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_dynamo/__init__.py", line 1, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_dynamo/convert_frame.py", line 31, in <module>
    from .eval_frame import always_optimize_code_objects, skip_code, TorchPatcher
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_dynamo/eval_frame.py", line 51, in <module>
    from . import config, convert_frame, external_utils, skipfiles, utils
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_dynamo/skipfiles.py", line 72, in <module>
    ] + [
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_dynamo/skipfiles.py", line 74, in <listcomp>
    _module_dir(m)
  File "/home/chen/my-project/text-generation-python-client/out/main.dist/lib/torch/_dynamo/skipfiles.py", line 62, in _module_dir
    return _strip_init_py(m.__file__)
AttributeError: module 'abc' has no attribute '__file__'. Did you mean: '__name__'?
```

**Comment by kayhayen** [comment]
With no reproducer, I will have to consider this as invalid unfortunately.

**Comment by wszgrcy** [comment]
> With no reproducer, I will have to consider this as invalid unfortunately.

the demo like this [https://www.philschmid.de/fine-tune-flan-t5-peft](https://www.philschmid.de/fine-tune-flan-t5-peft)
I use Huggingface `Trainer`
`--nofollow-import-to torch,transformers,peft,datasets`
after build I pip install in `lib` folder (with  sys.path.append(lib_dir))
When I didn't use `Trainer` before, it worked normally
I trace the source code `skipfiles.py`
```py
#....other code
def _module_dir(m: types.ModuleType):
    return _strip_init_py(m.__file__)# if input `abc` throw error
SKIP_DIRS = [
    # torch.*
    _module_dir(torch),
    # torchdynamo.*
    os.path.dirname(__file__) + "/",
    "<frozen importlib",
    "<__array_function__ internals>",
] + [
    # skip some standard libs
    _module_dir(m)
    for m in (
        abc, #--------------> no __file__
        collections,
        contextlib,
        copy,
        copyreg,
        dataclasses,
        enum,
        functools,
        importlib,
        inspect,
        linecache,
        logging,
        multiprocessing,
        operator,
        os,
        posixpath,
        random,
        re,
        selectors,
        signal,
        tempfile,
        threading,
        tokenize,
        traceback,
        types,
        typing,
        unittest,
        weakref,
        _collections_abc,
        _weakrefset,
    )
]
#...other code
```

**Comment by kayhayen** [comment]
it seems all packages that are technical, and `abc` is on recent enough Python3, but also `encodings` which is everywhere, at some point started having only `__path__` and no `__file__` and the code that goes over the technical imports to correct the `__file__` values for anything not built-in checked for presence of `__file__` before setting it. In Python2 it wasn't like that, in 3.8 it was, I do not care much whne it really started, I just added the check on `__path__` presence as well.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Since it might be an invasive change, potentially breaking, I consider this should be done only for the new release 1.8 and not as a hotfix of 1.7 which this could also be.

**Comment by kayhayen** [comment]
This is part of the current pre-release and will be part of 1.8

**Comment by wszgrcy** [comment]
> ```python
> if input `abc` throw error
> ```

I use development versiong`1.8rc.3`.But the error still exists,should I add any options?

**Comment by kayhayen** [comment]
Uhm, that's correct. No idea why, but I had analysed, that `encodings` would have to have the same issue, and it does. So for this code:

```
import encodings
print(encodings.__file__)
import abc
print(abc.__file__)
```

The first one works, and the second does not, which is very strange of course. Maybe the loading of packages from bytecode that is not technical, does not set it too, and that's a separate bug.

**Comment by kayhayen** [comment]
So, the `time` module is built-in and has no `__file__` and that's how we recognize those in the respective code. The `abc` module however needs it. We might have to check the `__loader__` and do corrections if it was the `FrozenImporter` which apparently doesn't do it, or maybe better use `sys.builtin_module_names` to identify them.

**Comment by kayhayen** [comment]
This fix is on factory again, I wasn't aware that for non-packages `__file__` is used as well. Obviously going to be used a lot less, since they do not have a folder to care about, but compatibility rules. The `sys.builtin_module_names` makes it easily work on all Python versions.

**Comment by kayhayen** [comment]
This is on develop now, and will be in 1.8 release too.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
