### ISSUE TITLE
Bug: Lightning - "AttributeError: module 'os' has no attribute '__file__'"

### ISSUE THREAD

**Issue by andreijw** [Nuitka/Nuitka#2462]
Hello, I am running into the following error after build when I use the lightning module and call the predict function on the trainer:
```AttributeError: module 'os' has no attribute '__file__'```

Here is the output of my ` python -m nuitka --version`
`1.8.2`
`Commercial: None`
`Python: 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]`
`Flavor: Fedora Python`
`Executable: /home/ajaume/foundation-seismic-modules/nuitka_env/bin/python`
`OS: Linux`
`Arch: x86_64`
`Distribution: Rhel (based on Fedora) 8.8`
`Version C compiler: /usr/lib64/ccache/gcc (gcc).`

`cat /etc/os-release/:`
`NAME="Red Hat Enterprise Linux"`
`VERSION="8.8 (Ootpa)"`
`ID="rhel"`
`ID_LIKE="fedora"`
`VERSION_ID="8.8"`
`PLATFORM_ID="platform:el8"`
`PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"`
`ANSI_COLOR="0;31"`
`CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"`
`HOME_URL="https://www.redhat.com/"`
`DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"`
`BUG_REPORT_URL="https://bugzilla.redhat.com/"`

`REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"`
`REDHAT_BUGZILLA_PRODUCT_VERSION=8.8`
`REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"`
`REDHAT_SUPPORT_PRODUCT_VERSION="8.8"`

This is a RedHat server, but I also have the same results on an Ubuntu and Debian server. I also tested with Python 3.10 and Python 3.11

[Update: (As of 10/02/2023 the PR has been merged and this first issue is fixed)]
The first error I get is related to the version info file for the lighting module. But I have already made a PR to address that issue.
[PR-2461](https://github.com/Nuitka/Nuitka/pull/2461). It's a simple error that happens when the module looks for a version.info file that is not currently being copied over.

`(nuitka_env) [user@spark-devops-shell-rhel8 test_nuitka]$ ./__main__.dist/__main__.bin  Traceback (most recent call last): File "/home/user/test_nuitka/__main__.dist/__main__.py", line 3, in <module> File "<frozen importlib._bootstrap>", line 1178, in _find_and_load File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "/home/user/test_nuitka/__main__.dist/lightning/__init__.py", line 17, in <module lightning> File "<frozen importlib._bootstrap>", line 1178, in _find_and_load File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "/home/user/test_nuitka/__main__.dist/lightning/__version__.py", line 8, in <module lightning.__version__> FileNotFoundError: [Errno 2] No such file or directory: '/home/user/test_nuitka/__main__.dist/lightning/version.info' `

While the PR is getting merged, I resolved that error by manually creating the directory and copying the file over from my venv:
`mkdir -p __main__.dist/lightning`
`cp ../nuitka_env/lib/python3.11/site-packages/lightning/version.info __main__.dist/lightning/`

Then the Nutika artifact executes just fine until it gets to the final error:
```
  File "/home/user/test_nuitka/__main__.dist/__main__.py", line 77, in <module>
  File "/home/user/test_nuitka/__main__.dist/__main__.py", line 68, in denoiser_main
  File "/home/user/test_nuitka/__main__.dist/lightning/pytorch/trainer/trainer.py", line 841, in predict
  File "/home/user/test_nuitka/__main__.dist/lightning/pytorch/utilities/compile.py", line 119, in _maybe_unwrap_optimized
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/test_nuitka/__main__.dist/torch/_dynamo/__init__.py", line 1, in <module torch._dynamo>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/test_nuitka/__main__.dist/torch/_dynamo/convert_frame.py", line 17, in <module torch._dynamo.convert_frame>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/test_nuitka/__main__.dist/torch/_dynamo/eval_frame.py", line 40, in <module torch._dynamo.eval_frame>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/test_nuitka/__main__.dist/torch/_dynamo/skipfiles.py", line 86, in <module torch._dynamo.skipfiles>
  File "/home/user/test_nuitka/__main__.dist/torch/_dynamo/skipfiles.py", line 76, in _module_dir
AttributeError: module 'os' has no attribute '__file__'
```

I installed nuitka through pip into a virtual environment `pip install Nuitka==1.8.2`
I created a new virtual environment and minimal code to reproduce the issue. Here are the requirements.txt file contents
`Nuitka==1.8.2`
`ordered-set==4.1.0`
`torch-dct==0.1.6`
`--extra-index-url https://download.pytorch.org/whl/cu117`
`torch==2.0.1+cu117`
`torchvision>=0.15.2+cu117`
`torchmetrics==1.1.0`
`lightning==2.0.5`

Pip Freeze output:
`aiohttp==3.8.5`
`aiosignal==1.3.1`
`anyio==3.7.1`
`arrow==1.2.3`
`async-timeout==4.0.3`
`attrs==23.1.0`
`backoff==2.2.1`
`beautifulsoup4==4.12.2`
`blessed==1.20.0`
`certifi==2023.7.22`
`charset-normalizer==3.2.0`
`click==8.1.7`
`cmake==3.27.5`
`croniter==1.4.1`
`dateutils==0.6.12`
`deepdiff==6.5.0`
`fastapi==0.103.1`
`filelock==3.12.4`
`frozenlist==1.4.0`
`fsspec==2023.9.2`
`h11==0.14.0`
`h5py==3.9.0`
`idna==3.4`
`inquirer==3.1.3`
`itsdangerous==2.1.2`
`Jinja2==3.1.2`
`lightning==2.0.5`
`lightning-cloud==0.5.38`
`lightning-utilities==0.9.0`
`lit==17.0.1`
`markdown-it-py==3.0.0`
`MarkupSafe==2.1.3`
`mdurl==0.1.2`
`mpmath==1.3.0`
`multidict==6.0.4`
`networkx==3.1`
`Nuitka==1.8.2`
`numpy==1.26.0`
`ordered-set==4.1.0`
`packaging==23.1`
`pandas==2.1.1`
`Pillow==10.0.1`
`psutil==5.9.5`
`pydantic==1.10.12`
`Pygments==2.16.1`
`PyJWT==2.8.0`
`python-dateutil==2.8.2`
`python-editor==1.0.4`
`python-multipart==0.0.6`
`pytorch-lightning==2.0.9`
`pytz==2023.3.post1`
`PyYAML==6.0.1`
`readchar==4.0.5`
`requests==2.31.0`
`rich==13.5.3`
`six==1.16.0`
`sniffio==1.3.0`
`soupsieve==2.5`
`starlette==0.27.0`
`starsessions==1.3.0`
`sympy==1.12`
`torch==2.0.1+cu117`
`torch-dct==0.1.6`
`torchmetrics==1.1.0`
`torchvision==0.15.2+cu117`
`tqdm==4.66.1`
`traitlets==5.10.1`
`triton==2.0.0`
`typing_extensions==4.8.0`
`tzdata==2023.3`
`urllib3==2.0.5`
`uvicorn==0.23.2`
`wcwidth==0.2.6`
`websocket-client==1.6.3`
`websockets==11.0.3`
`yarl==1.9.2`
`zstandard==0.21.0`

This is my folder structure:
`test:`
`    -__init__.py`
`    - setup.py`
`    - test_nuitka`
`         - __init__.py`
`         - requirements.txt (shown above)`
`         - __main__.py`
`         - smldwrapper.py`
`         - utils.py`
`         -  __main__.dist (nuitka artifact)`

I added various log statements in the file to be able to pin point where the main issue happens. If I go in the test_nuitka dir and run the python __main__.py, the code completes without any issues. `python3 ./__main__py` and I see the line `nuitka execution complete` I tried to create the minimal working test set that I could include here.

These are the files I included:

- `__main__.py` :

```python

import os
import lightning as L
import lightning.pytorch as pl
import torch

from test_nuitka.smldwrapper import SMLDWrapperModule
from test_nuitka.utils import load_data

def main(runtime_config_path=""):
    print(f"current path - {os.getcwd()}")
    config = {
        "output-dir": "./output",
        "strategy": "ddp",
        "dataloader_collate_fn": "identity",
        "writer_collate_fn": "default",
        "num-data-workers": "6",
        "batch-size": "2",
        "job-id": "123-job-id",
    }

    dataloader, norm_factor = load_data(
        start_index=1,
        end_index=4,
        config=config,
        batch_size=int(config["batch-size"]),
        num_workers=int(config["num-data-workers"]),
    )

    trainer = L.Trainer(
        accelerator="auto",
        strategy=config["strategy"],
    )

    print(
        f'Starting trainer with the {config["strategy"]} strategy '
        f"and {type(trainer.accelerator)}"
    )

    # I'm discovering the device in this way because of the way
    # SMLDRunnerVOL is currently loading itself onto a device
    # manually. This shouldn't be necessary as we move to newer
    # lightning modules. Ideally the accelerator should take care
    # of things like this. -- Josh

    if isinstance(trainer.accelerator, pl.accelerators.cuda.CUDAAccelerator):
        print("using cuda acceleration")
        smld_device = torch.device("cuda")
    elif isinstance(
        trainer.accelerator,
        pl.accelerators.cpu.CPUAccelerator,
    ):
        print("using cpu acceleration")
        smld_device = torch.device("cpu")
    else:
        if torch.cuda.is_available():
            smld_device = torch.device("cuda")
        else:
            smld_device = torch.device("cpu")

        print(
            f"WARNING: unhandled accelerator {type(trainer.accelerator)}. "
            f"using {smld_device}"
        )

    print(f"before trainer.predict")
    # Comment this line out to get the nutika to complete
    trainer.predict(
        model=SMLDWrapperModule(),
        dataloaders=[dataloader],
    )
    print(f"nuitka execution complete")


if __name__ == "__main__":
    main()
```
- `smldwrapper.py`:
```python
import lightning.pytorch as pl


class SMLDWrapperModule(pl.LightningModule):
    def __init__(self):
        print("inside init")
        super().__init__()
        print("after constructor init")

    def setup(self, stage):
        print(f"inside setup - {stage}")

    def predict_step(self, batch, batch_ixs):
        print(f"inside predict - {batch_ixs}")
        preds = []
        print(f"Batch Complete - {batch_ixs}")
        preds.append(len(batch))
        return preds

```

- `utils.py`:
```python
from torch.utils.data import DataLoader, Dataset
from torch.utils.data.dataloader import default_collate


class SliceDataset(Dataset):
    """
    Create data loader to distribute across one to many gpus
    """

    def __init__(self, start_index, end_index, config):
        self.norm_factor = 1
        self.start_index = start_index
        self.end_index = end_index
        self.config = config

    def __getitem__(self, index):
        slice_index = self.start_index + index
        slc, idstr = (slice_index, f"cl-{slice_index}")
        img_vol, vol_slc, vel_slc = slice_index, slice_index, slice_index

        return (slice_index, idstr, img_vol, vol_slc, vel_slc)

    def __len__(self):
        return abs(self.end_index - self.start_index)


def load_data(start_index, end_index, config, batch_size=32, num_workers=4):
    """
    Create a pytorch DataLoader to distribute data across 1 to many gpus
    """
    dataset = SliceDataset(
        start_index=start_index,
        end_index=end_index,
        config=config,
    )

    return (
        DataLoader(
            dataset=dataset,
            batch_size=batch_size,
            num_workers=num_workers,
            collate_fn=dataloader_collate_fn(config),
        ),
        dataset.norm_factor,
    )


def no_collate(x):
    return x


def configured_collate_fn(config, key):
    collate_fn_name = config.get(key, "default")
    if collate_fn_name == "default":
        return default_collate
    elif collate_fn_name == "identity":
        return no_collate
    else:
        raise ValueError(f"Unrecognized collator function {collate_fn_name}")


def dataloader_collate_fn(config):
    return configured_collate_fn(config=config, key="dataloader_collate_fn")


def writer_collate_fn(config):
    return configured_collate_fn(config=config, key="writer_collate_fn")
```

It's all pretty standard PyTorch classes and imports. If in __main__.py we comment out the line 68  `trainer.predict ...` and build the artifact, then execution completes as expected. But calling it causes the error I posted above.

I build the nuitka artifact with the following command from the test_nuitka dir:
`python3 -m nuitka --standalone --lto=no --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-IPython-mode=nofollow --noinclude-dask-mode=nofollow --noinclude-numba-mode=nofollow --nofollow-import-to=sqlalchemy --nofollow-import-to=pip --nofollow-import-to=tornado --nofollow-import-to=jinja2 --nofollow-import-to=lxml --nofollow-import-to=networkx --nofollow-import-to=contourpy --nofollow-import-to=charset-normalizer --nofollow-import-to=cmake --nofollow-import-to=plotly  --nofollow-import-to=seaborn --nofollow-import-to=filelock --nofollow-import-to=triton --remove-output __main__.py`

**Comment by kayhayen** [comment]
This is part of the 1.8.3 release I just made.

**Comment by kayhayen** [comment]
This is not reproducible for me with simple examples, I believe the `os` module has a `__file__` most certainly, and this could only come through some form of corruption. Can you provide the test case as a zip file for my convenience, since I am guessing I need to be very close to your code.

**Comment by andreijw** [comment]
Hello @kayhayen thanks for your help.

I have created a zip file with all the requirements to reproduce the issue I am facing. In the zip file, you will find all the required Python files, requirements.txt to create the virtual environment, and the command I used to build the project. Let me know if you require anything else from me. 

[test_nuitka.zip](https://github.com/Nuitka/Nuitka/files/12807230/test_nuitka.zip)

Regards,

Andrei Jaume

**Comment by andreijw** [comment]
I verified that this sample zip has everything needed to reproduce the issue. It has a requirements file with the minimum required packages on a fresh virtual env, has a README with the exact command I used to build the nuitka artifact, and the minimum example Python classes needed. Also, I was wondering if we could move this issue back to "Open" since I am still facing this bug. 

Let me know if this works for you.

Regards,

Andrei Jaume.

**Comment by kayhayen** [comment]
So, something bad encountered, when I ran your example:

```
  File "/home/hayen/.local/lib/python3.10/site-packages/huggingface_hub/utils/tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
  File "/home/hayen/repos/Py2C/nuitka/build/inline_copy/tqdm/tqdm/auto.py", line 29, in <module>
    from .asyncio import tqdm as asyncio_tqdm
ModuleNotFoundError: No module named 'tqdm.asyncio'
```

That should never happen, the inline copy of Nuitka sneaks into the compilation there.

**Comment by kayhayen** [comment]
This is because we now load `huggingface_hub` at compile time, and it uses `tqdm` like Nuitka, but ought to be ran from a different path.

**Comment by andreijw** [comment]
Hey @kayhayen ok I think I was specifically ignoring tqdm in my nuitka build command. I just updated that and ran it again, using the 1.8.3 nutika release and here is the output I get, it starts to go into the lightning module and then it fails on the predict step. I reattached an updated zip file with an updated build command on the README.md
[test_nuitka.zip](https://github.com/Nuitka/Nuitka/files/12849191/test_nuitka.zip)


``` bash
(nuitka_env) [ajaume@spark-devops-shell-rhel8 test_nuitka]$ ./__main__.dist/__main__.bin 
current path - /home/ajaume/foundation-seismic-modules/test_nuitka
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py:67: UserWarning: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `lightning.pytorch` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
Starting trainer with the ddp strategy and <class 'lightning.pytorch.accelerators.cuda.CUDAAccelerator'>
using cuda acceleration
before trainer.predict
inside init
after constructor init
Traceback (most recent call last):
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/__main__.py", line 77, in <module>
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/__main__.py", line 68, in denoiser_main
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/lightning/pytorch/trainer/trainer.py", line 841, in predict
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/lightning/pytorch/utilities/compile.py", line 119, in _maybe_unwrap_optimized
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/torch/_dynamo/__init__.py", line 1, in <module torch._dynamo>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/torch/_dynamo/convert_frame.py", line 17, in <module torch._dynamo.convert_frame>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/torch/_dynamo/eval_frame.py", line 40, in <module torch._dynamo.eval_frame>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/torch/_dynamo/skipfiles.py", line 86, in <module torch._dynamo.skipfiles>
  File "/home/ajaume/foundation-seismic-modules/test_nuitka/__main__.dist/torch/_dynamo/skipfiles.py", line 76, in _module_dir
AttributeError: module 'os' has no attribute '__file__'
(nuitka_env) [ajaume@spark-devops-shell-rhel8 test_nuitka]$
```
[test_nuitka.zip](https://github.com/Nuitka/Nuitka/files/12849193/test_nuitka.zip)

**Comment by kayhayen** [comment]
I was not saying you have this issue, it's just a regression of develop that I noted. When debugging issues, I do it on develop, and so I fix this first, before resuming, which it seems I did. And now I have encountered an issue, where when I used --python-flag=-m which may or may not have been a good idea, it was giving me a `KeyError` for `__main__` that I do not like. These are more like notes to self. So I didn't reproduce it yet myself, but once these regressions are fixed, I probably will.

**Comment by kayhayen** [comment]
I was not able to see this issue, I believe for myself. Can you retry with current factory branch? Also I was not seeing the KeyError anymore, which is strange.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by andreijw** [comment]
Trying it out now. Thanks a lot for the updates

**Comment by andreijw** [comment]
Hello @kayhayen . 
I tried using develop build 1.8.4 and 1.8.5 and got the same issue as what is posted in this ticket.
This is what the build output looks like:
[output.txt](https://github.com/Nuitka/Nuitka/files/13220240/output.txt)

There seem to be no issues, but then when I run it I get the following error still.:
[error.txt](https://github.com/Nuitka/Nuitka/files/13220316/error.txt)

 Let me know if there is anything else you need from me / would like to see included.

**Comment by doradsoft** [comment]
Hello @kayhayen .
We are encountering this as well.
Please tell if you need some additional input.

**Comment by doradsoft** [comment]
Here is an additional reproduce:

```
We must use staging version until https://github.com/Nuitka/Nuitka/issues/2375 is merged.

- How did you install Nuitka and Python
`pip install Nuitka-commercial-staging.zip`
no `virtualenv`.


<details>
  <summary>The specific PyPI names and versions</summary>
  ```
absl-py==2.0.0
accelerate==0.24.0
aiohttp==3.8.6
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.1.0
bitsandbytes==0.41.1
cachetools==5.3.2
certifi==2023.7.22
charset-normalizer==3.3.0
click==8.1.7
datasets==2.14.5
deepspeed==0.9.1
dill==0.3.7
evaluate==0.4.1
filelock==3.12.4
frozenlist==1.4.0
fsspec==2023.6.0
google-auth==2.23.3
google-auth-oauthlib==1.1.0
grpcio==1.59.0
hjson==3.1.0
huggingface-hub==0.17.3
idna==3.4
iniconfig==2.0.0
Jinja2==3.1.2
joblib==1.3.2
Markdown==3.5
MarkupSafe==2.1.3
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
networkx==3.2
ninja==1.11.1.1
np==1.0.2
Nuitka @ file:///python-packages/Nuitka-commercial-staging.zip#sha256=48db0d6f1b455036c1353af1c2df7c1cb2325333b2f4c06d1cface463dc50cdb
numpy==1.26.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
ordered-set==4.1.0
packaging==23.2
pandas==2.1.1
pluggy==1.3.0
protobuf==3.20.3
psutil==5.9.6
py-cpuinfo==9.0.0
pyarrow==13.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==1.10.13
pytest==7.4.3
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.10.3
requests==2.31.0
requests-oauthlib==1.3.1
responses==0.18.0
rsa==4.9
safetensors==0.4.0
scikit-learn==1.3.2
scipy==1.11.3
sentencepiece==0.1.99
six==1.16.0
sympy==1.12
tensorboard==2.15.0
tensorboard-data-server==0.7.2
threadpoolctl==3.2.0
tokenizers==0.14.1
torch==2.1.0
tqdm==4.66.1
transformers==4.34.1
triton==2.1.0
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
Werkzeug==3.0.1
xformers==0.0.22.post7
xxhash==3.4.1
yarl==1.9.2
zstandard==0.21.0
  ```python
</details>

- Many times when you get an error from Nuitka, your setup may be special

Other programs do work. even one which includes `datasets`.

- Also supply a Short, Self Contained, Correct, Example
https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py

- Provide in your issue the Nuitka options used

`python -m nuitka --main=accelerate_reproduce.py --standalone --onefile --onefile-tempdir-spec="/tmp/onefile_casual_lm_training_%PID%_%TIME%" --static-libpython=no --include-distribution-metadata=accelerate --include-distribution-metadata=bitsandbytes --include-distribution-metadata=datasets --include-distribution-metadata=jinja2 --include-distribution-metadata=pandas --include-distribution-metadata=psutil --include-distribution-metadata=pytest --include-distribution-metadata=safetensors --include-distribution-metadata=torch --include-distribution-metadata=tqdm --include-distribution-metadata=transformers --include-distribution-metadata=huggingface-hub --include-distribution-metadata=scipy --include-distribution-metadata=tokenizers`

**Comment by kayhayen** [comment]
I am currently looking at adding containers for `run-inside-nuitka-container`, if somebody were to complete this for CentOS 8 that could be helpful, but I am bound to doing it anyway, if only for the purpose of broader compatibility testing, but #2520 will have priority first, but I guess, as part of that research, those containers will make sense. I already added all Fedora versions privately, so CentOS 7/8 will be trivial.

I would also be curious of you have any form of hardening active during compilation. I recall that FIPS or however it is called, is supposed to work nowadays, but there might be more.

**Comment by doradsoft** [comment]
I updated comment with Nuitka version, full Python version, flavor, OS, etc. As you can see in our case it's ubuntu (debian).

**Comment by kayhayen** [comment]
@doradsoft that will be extremely helpful. The Ubuntu is pretty old, but I do not consider it to be related to OS now anymore. Going to check it.

**Comment by kayhayen** [comment]
@doradsoft how did you install the Python, self compiled?

**Comment by doradsoft** [comment]
> @doradsoft that will be extremely helpful.
I sent it you via E-Mail. If not received or if you are having troubles running it, please let me know.
> The Ubuntu is pretty old
Yeah, it's intended as some of our clients have old machines as well as some of our regressions machines. 
> but I do not consider it to be related to OS now anymore.
Nevertheless I'm checking on a Ubuntu 23.04 right now, and will update with the results.
>Going to check it.
Thanks!
> @doradsoft how did you install the Python, self compiled?
You can inspect the Dockerfile I shared with you.
For 23.04 it would be different and more straight forward, let's wait until I would test it there and if it'll reproduces there as well I'll send another image and its Dockerfile.

**Comment by doradsoft** [comment]
It reproduces on ubuntu 23.04 with a straight forward python installation, I'll send the image and Dockerfile tomorrow.

**Comment by kayhayen** [comment]
So, thanks for the great help there, I will definitely put that to use, but I did print for my sanity with a very simple test, the os module file value, and low and behold, it's wrong (but present).

I am getting a value `/home/hayen/repos/Py2C/Mini.dist/python3.11/os.py` with Python3.11 and `/home/hayen/repos/Py2C/Mini.dist/os.py` with Python3.10, so there definitely is some compatibility stuff going on.

I have no clue where it comes from. It seems no Nuitka code is run in the importer, this is done by `FrozenImporter` as they effectively turned `os` into a standard frozen module, without me noticing so far. With 3.10 Nuitka loads the bytecode itself and constructs the value of `__file__` before execution and does so correctly. And 3.11 does it in the frozen importer, and then it's kind of wrong.

The frozen importer is avoided by Nuitka normally, but the `os` module is detected as frozen and then treated like a builtin module, previously only absurd modules like `this` had been frozen, or the import bootstrap of newer Pythons, but nothing too critical.

I am stomped right now how that happens. Not seeing anything in `FrozenImporter` dealings that would change or even create the `__file__` value.

**Comment by andreijw** [comment]
Would you advise in the meantime, to downgrade the python version to 3.10 instead?

**Comment by kayhayen** [comment]
I am as usual optimistic enough that once found, a solution is never far off. I wouldn't panic switch, but I have reason to believe this is going to turn out to be 3.11 specific. There is something fishy going on here. 

I am not sure why `os.__file__` is `None` for you in `torch` (for frozen modules imported during init, that would be normal to Nuitka, and there is code to correct that, but `os` is not one of them), but from what I am seeing, the `compile_bytecode` uses original compile time source paths, that these carry over into Nuitka compiled executable, and that would be where the `python3.11` is coming from, which is very bad. 

This is a hunch now, but I believe it's wrong in their code objects to boot with, and they have code to update the wrong `__file__` values to actual values later, but it fails miserably in doing that. I can of course recognize frozen modules, or disable them, or force `os` to be included and used through our loader. I am a bit annoyed at the wasted bytecode size. Also their list doesn't make a whole lot of sense to me:

```
>>> _imp._frozen_module_names()
['_frozen_importlib', '_frozen_importlib_external', 'zipimport', 'abc', 'codecs', 'io', '_collections_abc', '_sitebuiltins', 'genericpath', 
'ntpath', 'posixpath', 'os.path', 'os', 'site', 'stat', 'importlib.util', 'importlib.machinery', 'runpy', '__hello__', '__hello_alias__', 
'__phello_alias__', '__phello_alias__.spam', '__phello__', '__phello__.__init__', '__phello__.ham', '__phello__.ham.__init__', 
'__phello__.ham.eggs', '__phello__.spam', '__hello_only__']
```

**Comment by kayhayen** [comment]
So progress is unavoidable I guess:

```
strings Mini.dist/libpython3.11.so.1.0 | grep Hello
Hello world!
```

**Comment by kayhayen** [comment]
So... the https://bugs.python.org/issue45020 and https://bugs.python.org/issue21736 seem relevant, and this most likely is a kind of bug in CPython 3.11 introduces by these patches. I do not approve of this change at all. They statically make libpython larger than necessary, and even static linking might not even allow to solve it, or maybe even be the difference, if you compiled your 3.11 in a better way than I did. I am purposefully using bad options for the self compiled 3.11 so as to not require things. Maybe with a static libpython it would be possible to override it, but it will seriously complicate things for Nuitka.

However, I didn't find the python3.11 part of the file value for the `os` package in the libpython, so in all likelihood, it's being calculated somehow, and I would say in a buggy way. That can also be seen by the `encodings` package not having the issue. But maybe because it's a package.

**Comment by kayhayen** [comment]
For commercial users, the unprotected frozen `os` module is an attack vector, that will need changes in order to be disabled, I am going to recommend commercial users to avoid 3.11 if they seek maximal protection. I will however for 1.9 make changes that disable them, and turn them into useless bloat depending on the Python flavor. Updating the commercial container build for 3.11 to be able to avoid the then bloat is another thing, that I am not sure when I will have that.

**Comment by kayhayen** [comment]
So, actually I solved this frozen modules issue for 3.11 on the factory and staging branch now, Nuitka's `os` module compilation is now used, and frozen modules are ignored. I am currently working with the provided container files to extract something to use in my private/commercial testing, I will for commercial container builds eventually remove the overhead of the frozen modules for the Python3.11 builds, as they are now only bloatware. It seems though, that the ability to do that is not directly exposed to `configure` script at all, so we probably need some manual patching to get rid of them. Help is very welcome there.

But with that, I think your report is in all likelihood probably solved. I will turn back to the provided example only later though, so your reports of testing it would be valuable.

**Comment by doradsoft** [comment]
I confirm it works on ubuntu 16.04.

**Comment by kayhayen** [comment]
I think the implementation is actually hotfix capable. I might do a hotfix for 3.11 there, but it will take me a while before I have Nuitka-Watch to cover 3.11 on other OSes than macOS, or maybe it's good enough already. I am busy right now with stabilizing factory/staging however for the Qt changes needed, so maybe a 1.9 will still come earlier.

**Comment by andrybicio** [comment]
Same error here:

```
>  python -m nuitka --version
Commercial: None
Python: 3.11.4 (main, Aug 11 2023, 14:02:42) [GCC 9.4.0]
Flavor: pyenv
Executable: /home/andrea/.pyenv/versions/my_env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc).
```

```
> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

And it raises an error:
```
Traceback (most recent call last):
  File "/home/andrea/AI/main.dist/main.py", line 68, in <module>
  File "/home/andrea/AI/main.dist/src/networks/train_nets.py", line 29, in train_nets
  File "/home/andrea/AI/main.dist/src/networks/train_nets.py", line 30, in <genexpr>
  File "/home/andrea/AI/main.dist/torch/optim/sgd.py", line 26, in __init__
  File "/home/andrea/AI/main.dist/torch/optim/optimizer.py", line 266, in __init__
  File "/home/andrea/AI/main.dist/torch/_compile.py", line 22, in inner
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/andrea/AI/main.dist/torch/_dynamo/__init__.py", line 2, in <module torch._dynamo>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/andrea/AI/main.dist/torch/_dynamo/convert_frame.py", line 34, in <module torch._dynamo.convert_frame>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/andrea/AI/main.dist/torch/_dynamo/eval_frame.py", line 62, in <module torch._dynamo.eval_frame>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/andrea/AI/main.dist/torch/_dynamo/skipfiles.py", line 72, in <module torch._dynamo.skipfiles>
  File "/home/andrea/AI/main.dist/torch/_dynamo/skipfiles.py", line 62, in _module_dir
AttributeError: module 'os' has no attribute '__file__'
```

I see you have already solved and it seems it's related to Python 3.11, just wanted to give a heads-up.

**Comment by andreijw** [comment]
Ok thanks, I will try this out to see if it works for me as well.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.

**Comment by andreijw** [comment]
@kayhayen I can confirm that version 1.9 works on my sample test case. Thanks a lot for all your help and the effort you put into this. This was a major blocker for me and it is now Resolved.

Andrei Jaume
