### ISSUE TITLE
QtSql does not work with Nuitka on macOS

### ISSUE THREAD

**Issue by shyamnathp** [Nuitka/Nuitka#3079]
Hi,

I am one of the developers of PySide6. I noticed that when the module QtSql is used with Nuitka (also with the develop version), I get the following error:

`FATAL:     Error, problem with dependency scan of '~/pyside-setup/venv_11_7/lib/python3.11/site-packages/PySide6/Qt/plugins/sqldrivers/libqsqlodbc.dylib' with '/usr/local/opt/libiodbc/lib/libiodbc.2.dylib' please report the bug.`

I am almost sure that the error also exists with PyQt6 used with Nuitka.

**The entire command being run was:**
`python -m nuitka main.py --follow-imports --enable-plugin=pyside6 --quiet --noinclude-qt-translations --standalone --macos-create-app-bundle --noinclude-dlls=*.cpp.o --noinclude-dlls=*.qsb --noinclude-dlls=*.webp --macos-app-icon=/Users/qt/pyside-setup/sources/pyside-tools/deploy_lib/pyside_icon.icns --include-qt-plugins=accessiblebridge,platforminputcontexts,platforms/darwin,sqldrivers`

**What causes the error?**
The error is caused by Qt ODBC Sql Driver (libqsqlodbc.dylib) on macOS having a hard dependency on the ODBC library.

otool results:

```
./Qt/plugins/sqldrivers/libqsqlodbc.dylib (architecture x86_64): 
 /usr/local/opt/libiodbc/lib/libiodbc.2.dylib (compatibility version 4.0.0, current version 4.30.0)
 .........
```

As I talk to some experts at Qt, this design of hard depdendency was due to various reasons. The C++ deployment tool for macOS,
'[macdeployqt](https://doc.qt.io/qt-6/macos-deployment.html#the-mac-deployment-tool)' solves this issue by bundling the `libiodbc.2.dylib` library with the application package and using `install_name_tool` to modify the RPATH of `libqsqlodbc.dylib` to point to the patch where `libiodbc.2.dylib` is bundled within the application package. _Can something like this be done with Nuitka as well?_

Please find a simple PySide6 example to reproduce the issue:

```
import sys
from PySide6.QtWidgets import QApplication
from PySide6.QtSql import QSqlQuery

if __name__ == "__main__":
    app = QApplication(sys.argv)
    query = QSqlQuery()
    sys.exit(app.exec())

```

**System info:**
2.5rc5
Commercial:None
Python: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Flavor: Homebrew Python
Executable: /Users/qt/pyside-setup/venv_11_7/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 14.3
Version C compiler: /usr/bin/clang (clang 15

Corresponding issue on PySide: https://bugreports.qt.io/browse/PYSIDE-2835

**Comment by kayhayen** [comment]
That's not a big issue, I think I have seen similar cases before and will add an exception for allowed missing DLLs. I wasn't immediately able to reproduce it, I wonder why that is.

**Comment by kayhayen** [comment]
Ah yes, I forgot to include the SQL drivers plugins, then I have it too. I don't have the /usr/local/opt/libiodbc/lib/libiodbc.2.dylib package, how do I get it? Should I really have to install Postgres for that?

Typically we don't include system DLLs, it would appears that in this case, we can make an exception, and that would be OK. I am having right now this:

FATAL: Error, failed to find path /usr/local/opt/libiodbc/lib/libiodbc.2.dylib (resolved DLL to /usr/local/opt/libiodbc/lib/libiodbc.2.dylib) for /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PySide6/Qt/plugins/sqldrivers/libqsqlodbc.dylib from 'PySide6', please report the bug.

**Comment by shyamnathp** [comment]
This path error that Nuitka throws is expected and is correct. The problem is stock macOS does not have libiodbc.2.dylib (odbc driver). You will have to install it via brew and move it into `/usr/local/opt`

`brew install libiodbc`

Postgres is also a requirement. After installing libiodbc into /usr/local/opt, I belive Postgress 14 might also throw a path error which has the similar fix as libiodbc. I would have imagined that this would fix the error from Nuitka, but then I get the following error even when '/usr/local/opt/libiodbc/lib/libiodbc.2.dylib' exists.

`FATAL:     Error, problem with dependency scan of '~/pyside-setup/venv_11_7/lib/python3.11/site-packages/PySide6/Qt/plugins/sqldrivers/libqsqlodbc.dylib' with '/usr/local/opt/libiodbc/lib/libiodbc.2.dylib' please report the bug.`

This is the error I am confused about.

**Comment by kayhayen** [comment]
I checked your CPU arch, and it's arm64, so I wasn't think this was a Homebrew path, because those ones are automatically allowed for, just not found. Do you think it would also be acceptable for the CPython.

**Comment by shyamnathp** [comment]
as in, do you mean if the path is recognized by CPython? Then yes. I can run the example directly with the Python interpreter.

**Comment by kayhayen** [comment]
Homebrew Python is not CPython Official for the purposes of Nuitka. So I take you mean it runs with your Homebrew.

I think, obdc is something you install to the system, and it doesn't come with PySide6 or maybe Homebrew either. So not having said DLL should also reproduce on CPython, and this would have to be added to the list of forbidden DLLs, causing said plugin to not be included if that DLL is not found.

**Comment by kayhayen** [comment]
It doesn't trigger for me on PyPI package with on ARM, so I feel this is about mixed architectures in some way, so probably your Homebrew PySide6 is not working. Can you provide a more complete set of instructions, how you installed packages there?

Nuitka does the install name tool patching generically, but it wants to package the tools. Plugins that are x86_64 only, to be loaded into an ARM only compilation are kind of surprising sights and that's probably where Nuitka stumbles. It wouldn't want to consider the wrong architecture binary. Also I am not sure now, if you have ODBC manually installed or not.

**Comment by kayhayen** [comment]
For me, it does not exist, and that has to be considered tolerable. If it does exist for you and gives you this error, I wouldn't be surprised really.

**Comment by kayhayen** [comment]
My setup looks more healthy than yours for arches, but I would love to have Nuitka detect and handle it properly, so please don't change it until we got proper reporting and or handling, if x86_64 ODBC is actually supposed to work.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
The forbidden DLL approach is prevening incomplete DLLs from being included, which means they cannot become complete on end users systems and then used. The real solution would be to keep these broken dependencies unchanged and still carry said DLLs, but that's too much effort for now, and this makes most configurations work. If you wanted to distribute them, you would need to install their dependencies before compiling.

By including all plugins on macOS, I also identified one plugin in multimedia that has a similar issue.

**Comment by kayhayen** [comment]
Part of the current hotfix release 2.4.9

**Comment by kayhayen** [comment]
I am pretty sure I managed to reproduce it and have it fixed for my CPython, where I reproduced it, I am assuming you failed to properly update factory.

**Comment by shyamnathp** [comment]
i just checked again. I still get it. This is what my environment looks like:

```
OS: Darwin
OS Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Platform: macOS-14.3-arm64-arm-64bit
Processor: arm
Architecture: ('64bit', '')
Python Version: 3.12.6 (main, Sep 24 2024, 09:57:31) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Python Implementation: CPython
Python Compiler: Clang 15.0.0 (clang-1500.1.0.2.5)
Python Build: ('main', 'Sep 24 2024 09:57:31')
```

and my Python environment looks like:

```
Package            Version
------------------ -------
appdirs            1.4.4
Jinja2             3.1.4
MarkupSafe         3.0.1
Nuitka             2.5rc8
Nuitka             2.5rc8
ordered-set        4.1.0
pip                24.2
PySide6            6.7.3
PySide6_Addons     6.7.3
PySide6_Essentials 6.7.3
PyYAML             6.0.2
qtpip              0.1.3
setuptools         75.1.0
shiboken6          6.7.3
SQLAlchemy         2.0.35
tqdm               4.66.5
typing_extensions  4.12.2
zstandard          0.23.0
```

**Comment by kayhayen** [comment]
I don't think Nuitka ought to duplicate there, maybe you got two of them in use, one being old.
