### ISSUE TITLE
FATAL:  Error, problem with dependency scan of `cairo/_cairo.cpython-312-darwin.so`

### ISSUE THREAD

**Issue by KeJunMao** [Nuitka/Nuitka#3224]
## Environment

```bash
❯ python -m nuitka --version
2.5.4
Commercial: None
Python: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:28:27) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: ~/Workspace/t2m/.conda/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 10.16
Version C compiler: /usr/bin/clang (clang 14.0.3).
```

## Reproducible Example
test.py
```python
# nuitka-project: --standalone
import cairo
```

```
python -m nuitka test.py
Nuitka-Options: Used command line options: --standalone test.py
Nuitka: Starting Python compilation with Nuitka '2.5.4' on Python '3.12' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow
Nuitka-Plugins:anti-bloat: down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.              
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 14.0.3).
Nuitka-Scons: Scons: Inherited CPPFLAGS='-I/usr/local/opt/libffi/include' variable.
Nuitka-Scons: Scons: Inherited LDFLAGS='-L/usr/local/opt/libffi/lib' variable.
Nuitka-Scons: Backend linking program with 23 files (no progress information available for this stage).
Nuitka-Scons: Compiled 23 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 23
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/cairo/lib/libcairo.2.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libpng/lib/libpng16.16.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/fontconfig/lib/libfontconfig.1.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/freetype/lib/libfreetype.6.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libx11/lib/libX11.6.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxext/lib/libXext.6.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxrender/lib/libXrender.1.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxcb/lib/libxcb.1.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxcb/lib/libxcb-render.0.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxcb/lib/libxcb-shm.0.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/pixman/lib/libpixman-1.0.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxau/lib/libXau.6.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/opt/libxdmcp/lib/libXdmcp.6.dylib'
Nuitka-Inclusion: Not including system DLL '/usr/local/Cellar/libxcb/1.17.0/lib/libxcb.1.dylib'
FATAL:     Error, problem with dependency scan of '~/Workspace/t2m/.conda/lib/python3.12/site-packages/cairo/_cairo.cpython-312-darwin.so' with '/usr/local/opt/cairo/lib/libcairo.2.dylib' please report the bug.
```

**Comment by KeJunMao** [comment]
Just don't use conda

**Comment by kayhayen** [comment]
I try to have Anaconda working with Nuitka though, since it's a commonly used piece of software. I would have to check, but the path used, `/usr/local/opt/cairo/lib/libcairo.2.dylib` could be from Homebrew and be about a mixed environment, and maybe point out an inconsistency there.

Since however, I don't do x86_64 for Homebrew clearly anymore, I might be unable to reproduce that on arm64, but I will give it a quick shot for sure.

**Comment by kayhayen** [comment]
I think something from Homebrew bleeding over to Anaconda and CPython is indeed the issue. I am confused to see tcl 9 mentioned, what Python uses that, I thought Python has fixed ideas about those. I will think of ways how we can learn of what to make. Right now I am suspecting that Homebrew is in your PATH when you compile, is that true?

**Comment by KeJunMao** [comment]
I understand your concerns about potential conflicts between Homebrew, Anaconda, and CPython. To clarify, I'm not using the global Python installed by Homebrew. Instead, I've set up a virtual environment for my project. 

## case 1
```
❯ python -m nuitka --version
2.5.4
Commercial: None
Python: 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Flavor: Homebrew Python
Executable: ~/Workspace/t2m/.venv/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 13.6.7
Version C compiler: /usr/bin/clang (clang 14.0.3).
```
Can successfully build Cario

## case 2
```
❯ python -m nuitka --version
2.5.4
Commercial: None
Python: 3.12.7 (v3.12.7:0b05ead877f, Sep 30 2024, 23:18:00) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: ~/Workspace/t2m/.venv/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 13.6.7
Version C compiler: /usr/bin/clang (clang 14.0.3).
```

Fail, just like the first comment

> PS: You may have noticed that I tried different versions of Python; this was my quirky way of dealing with the tcl-tk issue, please don't mind that. Let's focus on the Cairo issue

**Comment by kayhayen** [comment]
Well, Nuitka surely can be confused by seeing two installations of Cairo DLLs, I assume that's what's going on. Since you have it with CPython too, I can try it, and also I can check out if I can have Cairo on x86_64 there, but I am not so sure how pip is going to react the be ran with arch x86_64 wrapping. That's an experiment worth doing anyway, maybe.

The tcl9 issue is interesting to me, but indeed, I can check that out separately.

**Comment by kayhayen** [comment]
So, CPython is out of the picture, because cairo uses GTK from the system, and that can be arbitrarily bad. In fact, only Anaconda stands a chance of providing a workable package potentially, and of course Homebrew maybe. But this is like on Windows, where people seem to use MSYS2 for anything using GTK.

Your Cairo installation will not be very revealing to me. I will first look at Anaconda, and see if it has that even.

**Comment by kayhayen** [comment]
So Anaconda worked for me, but arm of course:

```
conda install -c conda-forge pycairo cairo
```

It seems the proper Anaconda I have limited pycairo to before 3.11, but maybe I only needed to update it. I need to check how to have Anaconda for intel arch and it works too, once I ignore list a warning about symbols somehow warned about from the system DLL libiconv, maybe also Anaconda, I don't care, but Nuitka errors out on that without me allowing that.

**Comment by kayhayen** [comment]
Setting `CONDA_SUBDIR=osx-64` is enough to convince conda to create environments and install packages for that arch it seems, that was actually easy right there.

**Comment by kayhayen** [comment]
Only sad thing is that `--mode=app` doesn't work as expected due to a typo I made when adding that feature, so the old style app bundle option ought to be used I guess until I hotfix that too.

**Comment by kayhayen** [comment]
I added the otool improvements to factory, and --mode=app is working there now too, both of these things will be part of 2.5.5 once it comes out. I want to take a quick look at the tcl9 situation there, this should be easy to add to Nuitka I guess.

**Comment by KeJunMao** [comment]
Since I don't have an arm64 macOS, I attempted to use the cpython on GitHub Actions for Cross Compilation. The x86_64 builds successfully, but the arm64 does not, which is quite strange.

Do you have any suggestions

python (use pdm-setup actions)

```
Run file $(which python3)
/Users/runner/hostedtoolcache/Python/3.[12](https://github.com/clipturbo/clipturbo/actions/runs/12104160156/job/33747225762#step:4:13).7/arm64/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Users/runner/hostedtoolcache/Python/3.12.7/arm64/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Users/runner/hostedtoolcache/Python/3.12.7/arm64/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64
```

deps:
```
brew install tcl-tk@8 py3cairo
```

`pdm run nuitka --version` :
```
2.5.4
Commercial: None
Python: 3.12.7 (v3.12.7:0b05ead877f, Sep 30 2024, 23:18:00) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: ~/work/clipturbo/clipturbo/.venv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 14.7.1
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

error logs:

```
FATAL:     Error, problem with dependency scan of '~/work/clipturbo/clipturbo/.venv/lib/python3.12/site-packages/cairo/_cairo.cpython-312-darwin.so' with '/opt/homebrew/opt/cairo/lib/libcairo.2.dylib' please report the bug.
```

**Comment by kayhayen** [comment]
The improvements I made are now part of 2.5.5, for me those were necessary to use this with x86_64 on macOS, but as I said, these things are going to be very unreproducible. Also tcl9 ought to work now there too.

**Comment by kayhayen** [comment]
It's not happening for my Homebrew arm64 installation. Since this mixes pdm, GitHub Actions, and other things, I am not so sure, I want to go and reproduce it myself. So, can you tell me if `/opt/homebrew/opt/cairo/lib/libcairo.2.dylib` even exists, and if not, what variations of it would?

What I am suspecting, is that you compile in GitHub Actions, and your program wouldn't run to begin with, due to missing DLLs in your installation. Arguably this could be missing Homebrew dependencies and such, but it seems for me it works. I can see how it is hard to confirm it works on GitHub Actions. But it can turn out a way of wasting my time.

**Comment by KeJunMao** [comment]
Thank you for your quick reply, I'll create a minimal repro later!

**Comment by KeJunMao** [comment]
minimal repo: https://github.com/clipturbo/nuitka-3224

error log: https://github.com/clipturbo/nuitka-3224/actions/runs/12106495262/job/33752301613#step:9:46

**Comment by kayhayen** [comment]
But does /opt/homebrew/opt/cairo/lib/libcairo.2.dylib or anything like that even exist?

**Comment by KeJunMao** [comment]
yes, test `ls -al /opt/homebrew/opt/cairo/lib`
https://github.com/clipturbo/nuitka-3224/actions/runs/12106605382/job/33752544175#step:6:25

**Comment by kayhayen** [comment]
Can you show the arches of the relevant file, I kind of expect it to not be universal (both arches), or is it

**Comment by kayhayen** [comment]
Kind of surprises me right there. What I was imagining is that wrong arch DLLs get removed, and as such, probably your x86_64 binary is not going to work elsewhere. However, I think I need to enhance the tracing there, for us to know.

You can test if non-universal Python which Nuitka is going to be works by running "import cairo" or whatever it takes to load the DLL with `arch -arch arm64` which will make it forget the universal nature, or so I seem to recall. Same for `arch -arch x86_64` or so.

But I think it's proven that something is wrong. I think I fixed the DLL scanner to accept dylib and .so interchangeably, and the .2 ought to not change that, but it's probably that. But I guess, the DLL scanner ought to maybe provide a better record of what it tried and didn't work and why to locate it.

**Comment by kayhayen** [comment]
Ah, not even a suffix change, only the number, in that case, it would have to be a regression, but lets first add more tracing to see what is going on.

**Comment by KeJunMao** [comment]
I've tried many methods but still can't compile correctly (excluding conda). If my program is highly dependent on CPython, is it impossible to compile cairo?

Is there any way to force the specification of the location of the cairo DLL for compilation?

**Comment by kayhayen** [comment]
I am not sure if you mean what I mean when I say CPython, for me that's the official distribution, and Homebrew and GitHub Actions Python are instances of it.

The GTK is never part of packages from PyPI, but always from the system. That is true for all variants, on all OSes.

On macOS things are more difficult for DLL inclusion, because we get to parse and modify the DLLs so they can be made portable. And our detection goes wrong there for an essential DLL, so I think you will have to either figure out the bug in the locating code or wait for somebody to do it. There won't be any shortcuts to this, and while I don't think it's possible, I would also never waste my time on those where there are instead bugs of Nuitka to fix.

**Comment by KeJunMao** [comment]
I found that I only need to customize the `--user-package-configuration-file` option.

```yaml
- module-name: "cairo._cairo"
  import-hacks:
    - package-system-dlls: "yes"
      when: "macos"
```


However, because of this line, I am unable to override it, and it seems to conflict with the built-in configuration. Is there any way to merge configurations?

https://github.com/Nuitka/Nuitka/blob/c773db2d24b4a1566f9d1155933aeb034c37898c/nuitka/utils/Yaml.py#L104-L110


error: 
```bash
    assert key not in self.data, key
           ^^^^^^^^^^^^^^^^
AssertionError: cairo._cairo
FATAL: anti-bloat: Plugin issue while working on 'plugin initialization'. Please report the bug with the above traceback included.
```

**Comment by kayhayen** [comment]
We don't have merging, you may have to create a PR therefore. With Homebrew the setting should be unnecessary, since it automatically allows DLLs from its libraries, but maybe a folder is missing. With CPython, I think it is necessary indeed. Isn't the report about Homebrew though?

Ah, now that I think of it, maybe `isHomebrewPython()` is not true for Github Actions Python, and that would cause it to not run.

**Comment by kayhayen** [comment]
Interesting if this applies:

```
def isHomebrewPython():
    # spell-checker: ignore sitecustomize
    if not isMacOS():
        return False

    candidate = os.path.join(
        getSystemPrefixPath(), "lib", "python" + python_version_str, "sitecustomize.py"
    )

    if os.path.exists(candidate):
        with open(candidate, "rb") as site_file:
            line = site_file.readline()

        if b"Homebrew" in line:
            return True

    return False
```

Not at all unlikely, that the detection method fails for GitHub Actions Python. It takes precedence in flavor detection, to --version won't tell us, and is simply recognized like this:

```
def isGithubActionsPython():
    # spell-checker: ignore hostedtoolcache

    return os.getenv("GITHUB_ACTIONS") == "true" and getSystemPrefixPath().startswith(
        "/opt/hostedtoolcache/Python"
    )
```

It probably would explain why my local builds don't show it but GitHub does?

**Comment by kayhayen** [comment]
This code might not be running on Actions: 

```
    if isHomebrewPython():
        inside_paths.insert(0, getHomebrewInstallPath())
```

**Comment by kayhayen** [comment]
The enhancements made are part of the 2.5.6 hotfix I just made, however, it remains unclear if GitHub Actions Python is properly recognized as a homebrew Python or not, once I find the time, I will try and assert that in a factory build, just to be sure.

**Comment by kayhayen** [comment]
Someone needs to clarify whether GitHub Actions Python is indeed a Homebrew Python. I might add an assertion to it so my CI can verify it, and if it strikes we know more.

**Comment by Kevin-O-Hsu** [comment]
We still dont know, and I got the same problem when using github action python
```
Nuitka-Options: Used command line options: --onefile --include-data-dir=resources=resources --include-data-file=resources/singbox.exe=resources/singbox.exe --show-scons --windows-uac-admin --user-package-configuration-file=nuitka-playwright.yml --output-dir=cache --standalone XBOXY/xboxy.py
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 70, in withPluginProblemReporting
    yield
  File "C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line [11](https://github.com/Kevin-O-Hsu/XBOXY/actions/runs/12256485588/job/34191839067#step:5:12)1, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.[12](https://github.com/Kevin-O-Hsu/XBOXY/actions/runs/12256485588/job/34191839067#step:5:13).5\x64\Lib\site-packages\nuitka\plugins\standard\AntiBloatPlugin.py", line 55, in __init__
    NuitkaYamlPluginBase.__init__(self)
  File "C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages\nuitka\plugins\YamlPluginBase.py", line 20, in __init__
    self.config = getYamlPackageConfiguration()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages\nuitka\utils\Yaml.py", line 2[13](https://github.com/Kevin-O-Hsu/XBOXY/actions/runs/12256485588/job/34191839067#step:5:14), in getYamlPackageConfiguration
    _package_config.update(
  File "C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages\nuitka\utils\Yaml.py", line 108, in update
    assert key not in self.data, key
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: playwright
FATAL: anti-bloat: Plugin issue while working on 'plugin initialization'. Please report the bug with the above traceback included.
```

nuitka2.5.6 python3.12.5
It works perfectly when I use my own pc
Any temp solution for this?

**Comment by KeJunMao** [comment]
Your issue doesn't belong to this issue, But I'm doing it by overriding.

```
sed -i '' '108s/^/#/' $(pdm run python -c "import inspect;import nuitka.utils.Yaml as n;print(inspect.getfile(n))")
```

**Comment by kayhayen** [comment]
The assertion didn't trigger for all I know, so we are without reasons why it happens, if it still happens.

**Comment by kayhayen** [comment]
I am stupid it seems, it actually did trigger:

```
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Nuitka/Nuitka/nuitka/PythonFlavors.py", line 350, in isGithubActionsPython
    assert isHomebrewPython()
           ^^^^^^^^^^^^^^^^^^
AssertionError
```

From this code:

```
def isGithubActionsPython():
    # spell-checker: ignore hostedtoolcache

    result = os.getenv("GITHUB_ACTIONS") == "true" and getSystemPrefixPath().startswith(
        "/opt/hostedtoolcache/Python"
    )

    # To confirm that it's actually that flavor to us as well.
    if result:
        assert isHomebrewPython()

    return result
```

So it seems the Homebrew detection mechanism is either imperfect, or needs to allow for that. I think it's homebrew that they are using, so lets try and change this.

**Comment by kayhayen** [comment]
Can you retry with the factory branch on GitHub Actions Python, it should now be treated as a Homebrew and as such, I would expect it to also work like Homebrew does, although the home path detection might go wrong still, so it's not a 100%.

**Comment by kayhayen** [comment]
Part of the 2.5.7 release I just made.
