### ISSUE TITLE
Binaries compiled with a Python installed by `uv` fails on Ubuntu: `libpython3.13.so.1.0` not found

### ISSUE THREAD

**Issue by kdeldycke** [Nuitka/Nuitka#3325]
Tl;Dr: System Python installed by `actions/setup-python` is working but not the Python installed by `uv`.

I made up a simple project to demonstrate this issue: https://github.com/kdeldycke/nuitka-issue-3325

### Works with `actions/setup-python`

This project is a simple CLI compiled to a standalone binary on all major platforms (Ubuntu, macOS and Windows) and 2 different architectures (`x86_64` and `arm64`).

This is performed by a GitHub workflow available at: https://github.com/kdeldycke/nuitka-issue-3325/blob/main/.github/workflows/system-python.yaml

The process [works perfectly on all platforms](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13107996796).

That's why I love Nuitka and exclusively rely on it! :D

Note that in the logs, Nuitka is [picking the right Python version from the system](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13107996796/job/36565931945#step:7:14):

```text
Nuitka: Starting Python compilation with Nuitka '2.6.2' on Python (flavor GitHub Actions Python), '3.13' commercial grade 'not installed'.
```

### Issue with `uv`

Now let's modify the working workflow used above, and completely remove the use of `actions/setup-python`. Instead, we will rely on `uv` alone to install our target Python version, by invoking:

```shell-session
$ uv venv --python 3.13
```

That new workflow is available at: https://github.com/kdeldycke/nuitka-issue-3325/blob/main/.github/workflows/uv-python.yaml

Here is an explicit highlight of the differences between the two workflows:
```diff
$ diff -ru ./.github/workflows/system-python.yaml ./.github/workflows/uv-python.yaml        
--- ./.github/workflows/system-python.yaml	2025-02-03 10:49:36
+++ ./.github/workflows/uv-python.yaml	2025-02-03 10:49:36
@@ -6,7 +6,7 @@
 
 jobs:
 
-  system-python:
+  uv-python:
     strategy:
       matrix:
         os:
@@ -19,15 +19,12 @@
     continue-on-error: true
     steps:
       - uses: actions/checkout@v4.2.2
-      - uses: actions/setup-python@v5.4.0
-        with:
-          python-version: "3.13"
       - name: Install uv
         run: |
           python -m pip install "uv == 0.5.26"
       - name: Install Nuitka
         run: |
-          uv --no-progress venv
+          uv --no-progress venv --python 3.13
           uv --no-progress pip install "nuitka == 2.6.2"
 
       - name: uv run -m nuitka --version
```

Despite these differences, I expect no change in the results. But this is not the case as you can see in this run: https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13107996795

All the Ubuntu builds fail. The [binary is still produced on these platforms](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13107996795/job/36565931926#step:6:24), but running them [ends up with this error message](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13107996795/job/36565931926#step:8:5):

```text
my-cli-ubuntu-24.04.bin: error while loading shared libraries: libpython3.13.so.1.0: cannot open shared object file: No such file or directory
```

Note that in this case, Nuitka [report Python 3.13 flavor as unknown](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13107996795/job/36565931926#step:6:6):

```text
Nuitka: Starting Python compilation with Nuitka '2.6.2' on Python (flavor Unknown), '3.13' commercial grade 'not installed'.
```

### Context

This has been tested with:
- Latest `nuitka`: 2.6.2
- Latest `uv`: 0.5.26
- Latest Python: 3.13
- Latest `actions/setup-python`: 5.4.0

**Comment by kayhayen** [comment]
What happens when you enable --static-libpython=yes, does that work? Then it would become a question of identifying the Python flavor used to be that specific Python and default to it from `auto` or to recognize why the automatic detection doesn't do it. Does it warn about static libpython presence?

**Comment by kayhayen** [comment]
Amazing grace, do people using rust know anything about build systems at all, or how can this happen.

```
(uv-python)  K hayen@kayonuk: ~/repos/Py2C$ ldd /home/hayen/tests/uv-python/.venv/bin/python
        linux-vdso.so.1 (0x00007fff20905000)
        /home/hayen/tests/uv-python/.venv/bin/../lib/libpython3.13.so.1.0 => not found
```

I am very, very confused how this is executable at all.

**Comment by kayhayen** [comment]
So, it seems in `bin` there are symlinks to a real Python, and if I follow the symlink, `ldd` works better. I didn't know that about `ldd` that it doesn't resolve them, which kind of could lead to incompatible analysis, even in Nuitka, should DLLs just be linked into a directory.

**Comment by kayhayen** [comment]
So, I am assuming, the reason, the Python DLL is not located, is actually because of the symlink not being resolved, so adding a realpath or the symlink target there.

I switched to 3.7 to be sure it's not using anything from the system, so now I get this:

```
ldd `readlink bin/python`
        linux-vdso.so.1 (0x00007ffe92725000)
        libpython3.7m.so.1.0 => /home/hayen/.local/share/uv/python/cpython-3.7.9-linux-x86_64-gnu/bin/../lib/libpython3.7m.so.1.0 (0x00007fdcab200000)
```

**Comment by kayhayen** [comment]
So, their static link library is an artifact, that is practically useless on its own, since they don't also provide the link libraries for using Tcl, and trying to find those from the OS, along with many others is unusable. They ought to either remove it from their download or make it usable. I would of course prefer to have it usable, so UV-Python doesn't have to provide inferior performance with Nuitka compared to other Python flavors like Anaconda, Debian Python, Ubuntu Python, etc.

**Comment by kayhayen** [comment]
The `uv` has a strange behaviour in that it uses installed CPython if available and only downloads as necessary, making it unreliable if what you get is CPython flavor or UV-Python flavor, but it's kind of understandable. The downloaded 3.12.2 that I picked because it's not matching any installed 3.12 worked out of the box with the unknown flavor.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This will be in 2.6.3 hotfix shortly.

**Comment by kayhayen** [comment]
This is part of the current hotfix.

**Comment by kdeldycke** [comment]
Thanks @kayhayen for the details! I just updated the test case with the latest `nuitka == 2.6.4` and `uv == 0.5.28` versions.

But I [still have the same results](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13151107465/job/36698572940#step:8:5):
```text
my-cli-ubuntu-24.04.bin: error while loading shared libraries: libpython3.13.so.1.0: cannot open shared object file: No such file or directory
```

But note that this time, Nuitka is [properly reporting the Python flavor as coming from `uv`](https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13151107465/job/36698572940#step:6:6):
```text
Nuitka: Starting Python compilation with Nuitka '2.6.4' on Python (flavor UV-Python), '3.13' commercial grade 'not installed'.
```

**Comment by kdeldycke** [comment]
I also reported that behavior upstream at: https://github.com/astral-sh/uv/issues/11234

**Comment by kayhayen** [comment]
What compilation mode is that, standalone?

**Comment by kdeldycke** [comment]
> What compilation mode is that, standalone?

I assume yes, standalone, give these parameters:
```shell-session
$ nuitka --onefile --assume-yes-for-downloads ...
```

Feel free to ask me to try a couple of variations of forced parameters if you need more feedback! :)

**Comment by kayhayen** [comment]
So, I never used this method of invocation, and only used the `venv` approach with it activated, and I just verified that ". ~/tests/uv-python/.venv/bin/activate" works fine with Nuitka.

I have a bit of a harder time to use `--module` (and what should `--frozen` do) with Nuitka, since it requires an installation of Nuitka, I would probably find it hard to debug, but maybe in case of `--module` the invocation is very different, so don't use it, but Nuitka's runner. And if you can, please try Python3.12 just in case there is something different there, since I never tried 3.13 with uv-Python so far, and maybe that one is different. Make sure to not use system Pythons of course, so as to have the uv-Python for sure.

**Comment by geofft** [comment]
I think the high-level problem is that the compiled binary in the dist directory, even before getting packed anywhere, already doesn't run without `LD_LIBRARY_PATH` (which Nuitka does warn you about without `--onefile`), and needs either an rpath or a library dependency by absolute path.

Note that the uv-installed Python does this:

```
$ readelf -d .venv/bin/python | egrep '(NEEDED|RPATH|RUNPATH)'
 0x0000000000000001 (NEEDED)             Shared library: [$ORIGIN/../lib/libpython3.12.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libutil.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

Which is to say, it has an `$ORIGIN`-relative path in the name of the library dependency itself, _not_ an `$ORIGIN`-relative rpath. I see there's some handling in nuitka.freezer.DllDependenciesPosix for the `$ORIGIN` token showing up in an rpath, and injecting it into the environment when running `ldd`, but not for it showing up in the name of a library dependency. Maybe it is enough to also handle these tokens in library dependency names?

But another way of looking at the problem is that Nuitka should be compiling binaries with an appropriate `-Wl,-rpath,...` setting, and as far as I know, there isn't a good way to convey that via sysconfig. (You can convey it via pkg-config, but a) we don't currently do that, maybe we should, and b) I see your argument in #1761 against using it.) Do you know of something?

One thing you can do as a heuristic is to look for `sysconfig.get_var("PYTHON_BUILD_STANDALONE") == "1"`, and if that's set, conclude that you need an rpath of `sysconfig.get_var("LIBDIR")`. I have a draft PR up for PyO3 that takes this approach at PyO3/pyo3#4890 to solve an analogous problem. I'd like to get upstream CPython to standardize on something, (maybe `"RELOCATABLE"`?).

(The other thing we could do is to set a soname in libpython of its own full path, but I've been hesitant to go that route because it means that a distribution from python-build-standalone won't work right out of the box, and you'll have to do some post-extraction patching. That would work for `uv` but maybe not for other consumers.)

**Comment by geofft** [comment]
(Oh, and the ldd thing turns out to be a known bug: https://sourceware.org/bugzilla/show_bug.cgi?id=25263 But I think you're already attempting to work around this by canonicalizing `sys.executable`.)

**Comment by kdeldycke** [comment]
Despite the latest fixes related to shared library (like https://github.com/Nuitka/Nuitka/commit/2cc95af024294b4f4f8204a3a757ef6a96b2bd6a and https://github.com/Nuitka/Nuitka/pull/3332), I can still reproduce this issue on GitHub with `uv 0.6.3` and `nuitka 2.6.7`:
```shell-session
/home/runner/work/nuitka-issue-3325/nuitka-issue-3325/my-cli-ubuntu-24.04.bin: error while loading shared libraries: libpython3.13.so.1.0: cannot open shared object file: No such file or directory
```

Source: https://github.com/kdeldycke/nuitka-issue-3325/actions/runs/13517179955/job/37768191123

**Comment by kdeldycke** [comment]
The newly released Nuitka 2.6.8 seems to fix the issue for me! 🎉

I can now rely on the uv-provided Python to build my binaries.

See before:

![Image](https://github.com/user-attachments/assets/30ec2b6e-a351-47fb-b4c8-d3068e398814)

And after:

![Image](https://github.com/user-attachments/assets/e4bc8028-224d-4bef-beca-dc9d1409c3ff)
