### ISSUE TITLE
Nuitka+OpenVINO can't read model (Docker environment)

### ISSUE THREAD

**Issue by f-domonkos** [Nuitka/Nuitka#3493]
## Short description
OpenVINO cannot read model files if I apply Nuitka on the code.

## Versions info
**python -m nuitka --version**
```
2.7.4
Commercial: None
Python: 3.11.12 (main, May  9 2025, 23:47:08) [GCC 12.2.0]
Flavor: Unknown
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 12
Version C compiler: /usr/bin/gcc (gcc 12).
```

**python -m pip list -v**
```
Package            Version  Location                                Installer
------------------ -------- --------------------------------------- ---------
Nuitka             2.7.4    /usr/local/lib/python3.11/site-packages pip
numpy              2.2.6    /usr/local/lib/python3.11/site-packages pip
openvino           2025.1.0 /usr/local/lib/python3.11/site-packages pip
openvino-telemetry 2025.1.0 /usr/local/lib/python3.11/site-packages pip
ordered-set        4.1.0    /usr/local/lib/python3.11/site-packages pip
packaging          25.0     /usr/local/lib/python3.11/site-packages pip
pip                24.0     /usr/local/lib/python3.11/site-packages pip
setuptools         65.5.1   /usr/local/lib/python3.11/site-packages pip
wheel              0.45.1   /usr/local/lib/python3.11/site-packages pip
zstandard          0.23.0   /usr/local/lib/python3.11/site-packages pip
```

## Nuitka command: 
`nuitka --standalone --include-data-files=model.bin=model.bin --include-data-files=model.xml=model.xml --enable-plugin=numpy --enable-plugin=anti-bloat main.py`

## Reproducable example
main.py
```
import openvino as ov
import os

print("START")
model_path_xml = os.path.join(os.path.dirname(__file__), "model.xml")
model_path_bin = os.path.join(os.path.dirname(__file__), "model.bin")
core = ov.Core()
ov_model = core.read_model(model=model_path_xml, weights=model_path_bin)

print("OK")
```

Dockerfile:
```
FROM python:3.11-slim AS build

# Install system dependencies for Nuitka
RUN apt-get update && \
    apt-get install -y binutils build-essential clang g++ gcc patchelf tk zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy app files
COPY main.py main.py
COPY model.bin model.bin
COPY model.xml model.xml

# Install Python dependencies
RUN pip install openvino==2025.1.0
RUN pip install nuitka==2.7.4

# Compile the code using Nuitka
RUN nuitka --standalone --include-data-files=model.bin=model.bin --include-data-files=model.xml=model.xml --enable-plugin=numpy --enable-plugin=anti-bloat main.py

WORKDIR main.dist

CMD [ "./main.bin" ]
```

Any OpenVINO model files (model.bin, model.xml).

## Output (error)
```
Traceback (most recent call last):
  File "/app/main.dist/main.py", line 8, in <module>
  File "/app/main.dist/openvino/_ov_api.py", line 580, in read_model
RuntimeError: Exception from src/inference/src/cpp/core.cpp:95:
Exception from src/inference/src/model_reader.cpp:154:
Unable to read the model: /app/main.dist/model.xml Please check that model format: xml is supported and the model is correct. Available frontends: jax pytorch tf
```
UPD.: Plus the "START" print message appears before/after.

## Details
I also tried...
- run the code in the container simply with Python; it worked
- read simple a text file and print the lines; it worked 
- different openVINO models; neither worked (with nuitka)
- run the nuitka command without plugins enabled
- specifying model paths with `os.path.join(os.path.dirname(sys.argv[0]), "model.xml")` and `os.path.join(__compiled__.containing_dir, "model.xml")`
- run the code on two different Linux servers

**Comment by SwakinX** [comment]
https://github.com/Nuitka/Nuitka/issues/1699#issuecomment-1465204977 deleting openvino.dll from top level dist folder

**Comment by f-domonkos** [comment]
Thanks @SwakinX for your reply!

The Docker environment is not Windows, so there is no openvino.dll, however I found that removing **libopenvino.so.2510** may fix the issue. Now, I get no errors for the read_model line. But I couldn't yet confirm that it doesn't cause other issues. 

Anyway, this still seems to be a bug of nuitka, manual modifications of the dist folder shouldn't be neccessary.

(I had checked the linked thread before but from the last comments I thought that bug was fixed.)

**Comment by f-domonkos** [comment]
Unfortunately, I get an other error with/without the libopenvino.so.2510 file, because there are no "available devices":
```
core = ov.Core()
print(f"Available devices: {core.available_devices}")
```
prints an empty list. Which makes inference impossible.

Once again, the same code, even with inference calls, runs without problem if nuitka is **not** involved (and prints ["CPU"] for the above lines).

**Comment by SwakinX** [comment]
> Unfortunately, I get an other error with/without the libopenvino.so.2510 file, because there are no "available devices":
> 
> ```
> core = ov.Core()
> print(f"Available devices: {core.available_devices}")
> ```
> 
> prints an empty list. Which makes inference impossible.
> 
> Once again, the same code, even with inference calls, runs without problem if nuitka is **not** involved (and prints ["CPU"] for the above lines).

On windows, after I deleted openvino.dll, an error of missing modules occurred. I copied all the files of the openvino library to the directory, and it ran normally. Then, when running, I tried to delete the files. The ones that couldn't be deleted in the end were the necessary libs. Of course, if you don't care about the space occupation, you can directly keep all the files. Perhaps you can try the same method to solve the problem

**Comment by f-domonkos** [comment]
Thanks again! If my understanding is correct however, it works for your Windows setup anyway (presumably fixed 2 years ago, based on your linked thread).

However for my Docker environment I have (at least) two problems, both are nonexistent if I run the code in the same environment without nuitka:
1) nuitka somehow messes up the .so files, which causes the crash already at the model read phase. This can be fixed by manually hacking out the libopenvino.so.2510 file after the nuitka compilation. I don't get missing modules without it.
2) Even with the hack (or without it), I cannot inference because I cannot access any "available device". I do not believe that randomly removing some other files should be the way to fix this (actually I have no idea how nuitka breaks it either). 

I truly appreciate the time and help already given. That said, after 1.5 months, I had hoped official support would try running the reproducer I provided and either confirm the bug or tell me what I’m doing wrong. Without that, I’m left to conclude that Nuitka is not only unstable in this case, but also lacks adequate support for these issues — so I’ll need to abandon it for now.

**Comment by SwakinX** [comment]
@f-domonkos It seems you misunderstood me. I'm not asking you to randomly delete other files. Instead, it asks you to move the entire openvino library file to the directory of the compiled program. This should solve the error caused by the missing library file (delete libopenvino.so.2510 first).

In fact, I don't think this issue has been fixed. I still have this problem when using the latest version of Nuitka. I need to delete openvino.dll first and then manually add the library file

**Comment by f-domonkos** [comment]
@SwakinX You are absolutely right, I misunderstood you. Copying the openvino folder still wasn't enough, but now I can finally make it work!

To sum it up:
- delete libopenvino.so.2510 from the dist folder that nuitka generates,
- delete libs and frontend folders from the dist/openvino (but keep _pyopenvino.so!),
- copy libs and frontend from where pip installed it into dist/openvino.

In my case I needed to add these lines in my Dockerfile after the nuitka command:
```
RUN rm main.dist/libopenvino.so.2510
RUN rm -R main.dist/openvino/frontend
RUN rm -R main.dist/openvino/libs
RUN cp -r /usr/local/lib/python3.11/site-packages/openvino/frontend main.dist/openvino/frontend
RUN cp -r /usr/local/lib/python3.11/site-packages/openvino/libs main.dist/openvino/libs

```

Thanks again for helping to find a workaround!

**Comment by fawney19** [comment]
我修改了 standard.nuitka-package.config.yml 后重新打包，修复了这个问题
```yml
- module-name: 'openvino'
  data-files:
    - dirs:
        - 'libs'
  dlls:
    - from_filenames:
        relative_path: 'libs'
        prefixes:
          - ''
        suffixes:
          - '.dll'
```

**Comment by kayhayen** [comment]
Damn auto-closes, I forgot to remove the fixes from the merge message, this will be part of 4.0.7 hotfix release once it's out.

**Comment by kayhayen** [comment]
This is part of the 4.0.7 hotfix release I made in the mean time.
