### ISSUE TITLE
Setuptools doesn't properly provide distutils with Nuitka on Python 3.12

### ISSUE THREAD

**Issue by timminator** [Nuitka/Nuitka#3501]
While compiling PaddleOCR using Python 3.12 on Windows I stumbled across another issue with this [file](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/fleet/utils/tensor_fusion_helper.py), specifically line 19 that still uses distutil. I got the same error I reported further down that I was able to recreate with a simple example.
I know distutil is deprecated and I also saw a similar issue with #3110 I think, but my example does work fine when just run via `python example.py`. Setuptools seems to be vendoring its own version of distutils until now.

Is there some setting that I'm missing or workaround for this issue? Thank you for your time!

```
2.7.6
Commercial: None
Python: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
Flavor: CPython Official
Executable: ~\Desktop\New folder (9)\venv-3.12\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe (cl 14.3).
```

I installed Python via the offical installer, created a virtual environment (venv) and installed nuitka in there.
 
Relevant packages:
```
setuptools  80.9.0  C:\Users\GPUVM\Desktop\New folder (9)\venv-3.12\Lib\site-packages pip
```

Example:
```
from distutils.util import strtobool

def main():
    test_vals = ["yes", "no", "true", "false", "0", "1", "maybe"]

    for val in test_vals:
        try:
            result = strtobool(val)
            print(f"{val!r} => {bool(result)}")
        except ValueError as e:
            print(f"{val!r} => ValueError: {e}")

if __name__ == "__main__":
    main()
```

Output after compiling:
```
Traceback (most recent call last):
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\example.py", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
```

Command used to compile:
```
python -m nuitka example.py --standalone
```

I also tried replacing `from distutils.util import strtobool` with `from setuptools._distutils.util import strtobool` but this just resulted in a different error (worked also just fine when run via python):
```
Traceback (most recent call last):
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\example.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\dist.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\config\pyprojecttoml.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\config\_apply_pyprojecttoml.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\extension.py", line 35, in <module>
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\monkey.py", line 48, in get_unpatched
  File "C:\Users\GPUVM\Desktop\NEDD60~1\EXAMPL~1.DIS\setuptools\monkey.py", line 68, in get_unpatched_class
AssertionError: distutils has already been patched by <class 'setuptools._distutils.extension.Extension'>
```

**Comment by Kevin-O-Hsu** [comment]
Read the docs first
Have you tried --include-package?

**Comment by kayhayen** [comment]
It would be wrong, if he had to use `--include-package`, so this looks like a genuine bug. As for your workaround attempt, always make sure it works with Python to debug with.

That said, this might be about anti-bloat stuff we do.

**Comment by kayhayen** [comment]
I think I have seen this before, setuptools includes an inline copy of distutils, which is no longer standard library, but on the file system it's named `_distutils` and that then is not recognized by adding to sys.path like setuptools does. In the compilation report, we see: `<path value="~/.local/lib/python3.12/site-packages/setuptools/_vendor" />` but if the module is named `distutils` then the `_distutils` folder is not going to cut it.

**Comment by kayhayen** [comment]
Setuptools does this: 

```
import setuptools._distutils as distutils; sys.modules["distutils"] = distutils
```

and it's forcing itself to be loaded before your program runs, because it can. Very ugly stuff. But it explains why the importing doesn't find it, and I doubt that --include-package=distutils would fare any better and indeed:

> FATAL: Error, failed to locate package 'distutils' you asked to include.

So, I recall working on this before, this issue is most definitely a duplicate and I didn't come up with a good solution at the time. What we have here is that a package directory is to be provided in order to even find it. I think for distutils yaml configuration to provide paths, so far, we only use it after we found it. But this means, we got to add something, that allows plugins to specify not just extra search paths based on the parent package, but extra full results actually.

**Comment by kayhayen** [comment]
So, the import mechanics, I made a refactoring, such that for "distutils", I have a place to hard code the `setuptools/_distutils` directory as a result, and then needed to also change code that inferred from the filename the module name, but instead to return it from the search. That seems to work. I am pitting new and old code against each other for everything but `distutils` in debug mode, before we can make it the default maybe for 2.8 release, but that change so far could be a 2.7 hotfix.

However, when checking for `distutils.util` it is not finding that now, while `distutils` is found.

**Comment by kayhayen** [comment]
So, passing more information upwards instead of reconstructing it seems to solve the issue, so now it's properly working as a package too. I have made the change in a fashion that it will only apply for `distutils` at first, and otherwise assert the identity of the result in debug mode, as I fear there will be regressions from this, as it was pretty messy what is supposed to be returned there, with relative imports being a thing.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
I am running Nuitka-Watch with --debug, so I can know it's fit for 2.8 and doesn't need more changes after me backporting it to 2.7 in a limited form, for develop and 2.8, after a hotfix release, I would then enable it by default in that way.

**Comment by timminator** [comment]
Thank you for your hard work! I tried out the factory version now, but unfortunately I got the following error, when compiling my example script from my initial post:
```
(venv-3.12) PS C:\Users\GPUVM\Desktop\New folder (10)> python -m nuitka example.py --standalone
Nuitka-Options: Used command line options:
Nuitka-Options:   example.py --standalone
Nuitka: Starting Python compilation with:
Nuitka:   Version '2.8rc7' on Python 3.12 (flavor 'CPython Official') commercial grade 'not installed'.
Problem with statement at example.py:1:
-> from distutils.util import strtobool

Nuitka: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'example.py', 'module_name':
Nuitka: <ModuleName '__main__'>, 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\__main__.py", line 209, in <module>
    main()
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\__main__.py", line 191, in main
    MainControl.main()
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\MainControl.py", line 1168, in main
    _main()
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\MainControl.py", line 996, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\MainControl.py", line 266, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 332, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 288, in makeOptimizationPass
    changed, micro_passes = optimizeModule(current_module)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 166, in optimizeModule
    return optimizeCompiledPythonModule(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 82, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\ModuleNodes.py", line 567, in computeModule
    result = module_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 139, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\FrameNodes.py", line 186, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 651, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 320, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 11675, in computeExpressionRaw
    expression = trace_collection.onExpression(self.subnode_module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 637, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 11914, in computeExpressionRaw
    return self.computeExpression(trace_collection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\ImportNodes.py", line 1047, in computeExpression
    module_filename = self._attemptFollow(module_name=imported_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\nodes\ImportNodes.py", line 940, in _attemptFollow
    Plugins.onModuleUsageLookAhead(
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\plugins\Plugins.py", line 1082, in onModuleUsageLookAhead
    ) = locateModule(
        ^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\importing\Importing.py", line 986, in locateModule
    findModule(
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\importing\Importing.py", line 478, in findModule
    found_module_name, module_filename, module_kind = _findModule(
                                                      ^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\importing\Importing.py", line 948, in _findModule
    module_search_cache[key] = _findModuleInPath(
                               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\importing\Importing.py", line 898, in _findModuleInPath
    found_module_name, module_filename, module_kind = _findModuleInPath2(
                                                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\importing\Importing.py", line 723, in _findModuleInPath2
    for fullname, _filename in listDirCached(candidate.found_in):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\importing\Importing.py", line 548, in listDirCached
    _list_dir_cache[path] = tuple(listDir(path))
                                  ^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\utils\FileOperations.py", line 355, in listDir
    real_path = getDirectoryRealPath(path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPUVM\Desktop\New folder (10)\venv-3.12\Lib\site-packages\nuitka\utils\FileOperations.py", line 270, in getDirectoryRealPath
    path = os.path.realpath(path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ntpath.py", line 706, in realpath
    path = normpath(path)
           ^^^^^^^^^^^^^^
TypeError: _path_normpath: path should be string, bytes or os.PathLike, not NoneType
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.
```

Installed version of setuptools was again `80.9.0`.

Here is also my crash report:

[nuitka-crash-report.xml.txt](https://github.com/user-attachments/files/20765251/nuitka-crash-report.xml.txt)

**Comment by kayhayen** [comment]
This is part of the current pre-release and will be in the 2.8 release, my attempts at testing with --debug for Nuitka-Watch were initially troubled by unrelated issues and require more time.

**Comment by timminator** [comment]
Sorry for bothering but I tried out the newest pre-release 2.8rc9 and im still seeing the crash I reported earlier. I just wanted to report my findings.

**Comment by kayhayen** [comment]
I just reconfirmed the original reproducer to still work for me, at least on Linux, the other crash you were speaking of ought to not happen, but `candidate.found_in` might be None, I have to check that.

**Comment by kayhayen** [comment]
Make it a new report with more details and updated description, so I can check this out. The mere distutils issue seems gone and this might be about something else.

**Comment by timminator** [comment]
Tested it again with the latest 2.8rc15 version and it worked flawlessly. So the issue must have been resolved since I tried it the last time in June. Thanks!

**Comment by kayhayen** [comment]
This is part of the stable release 2.8 that I just made.
