### ISSUE TITLE
Nuitka 2.7.16: FATAL while scanning OpenCV cv2.abi3.so when GStreamer is enabled (macOS arm64)

### ISSUE THREAD

**Issue by khayyat71** [Nuitka/Nuitka#3628]
# Bug Report

**IMPORTANT: Please review the
[Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue)
before submitting.**

______________________________________________________________________

## ⚠️ Pre-Submission Checklist

*Please check these items before submitting your report. This text can be removed.*

- [X] **Search Existing Issues:** Couldn’t find this exact crash for macOS + GStreamer dylibs.
- [X] **Python vs. Nuitka:** Running the code with CPython works (imports cv2, runs my app). Crash only during Nuitka build.
- [ ] **Test `develop` Branch:** Have you tried the `develop` version of Nuitka? It might contain a
  fix. Get it here https://nuitka.net/doc/download.html

______________________________________________________________________

**Discard everything above this line before submitting your issue.**

## 🐛 Bug Description

Nuitka crashes during dependency scan when cv2.abi3.so (OpenCV) is linked against GStreamer (Homebrew on macOS). The error consistently points to libgstbase-1.0.0.dylib.

This happens for both --standalone (app bundle) and --onefile builds. It reproduces with a minimal program that only does import cv2. The crash occurs even if I pass --noinclude-dlls to avoid bundling GStreamer/GLib/FFmpeg dylibs.
FATAL:     Error, problem with dependency scan of '~/studio1_exe/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so'
           with '/opt/homebrew/opt/gstreamer/lib/libgstbase-1.0.0.dylib' please report the bug.

## 🖥️ Environment

Nuitka: Version '2.7.16' on Python 3.11

Platform details:

macOS: 15.x (Sequoia) arm64 (Darwin 24.4.0)

Compiler: clang 17 (Apple), LTO on

Hardware: Apple Silicon (M-series)

### 2. How Nuitka and Python were Installed

Python: CPython 3.11.9 in a virtualenv

Nuitka: installed via pip in the venv

OpenCV (cv2): custom wheel built from source (opencv-python repo) with:

WITH_GSTREAMER=ON

WITH_FFMPEG=OFF

(sometimes also tried) VIDEOIO_PLUGIN_LIST=gstreamer

GStreamer: Homebrew (gstreamer 1.26.5, plus base/good/bad/libav plugins)

### 3. Relevant PyPI Packages and Versions

Please see python -m pip list -v (trimmed to the relevant ones):

opencv-python 4.11.0 (custom-built wheel; GStreamer YES, FFmpeg NO)

numpy 2.3.3

mediapipe (installed from PyPI)

PySide6 (installed from PyPI)

nuitka 2.7.16 

Also crashes if I add/omit these (doesn’t help):

--include-package=cv2

--nofollow-import-to=gi,pygobject,gst

--noinclude-dlls="/opt/homebrew/opt/gstreamer/lib/*.dylib"

--noinclude-dlls="/opt/homebrew/Cellar/gstreamer/*/lib/*.dylib"

--noinclude-dlls="/opt/homebrew/opt/glib/lib/*.dylib"

--noinclude-dlls="/opt/homebrew/Cellar/glib/*/lib/*.dylib"

and the analogous ffmpeg rules

### 3. Nuitka Command Line Options

python -m nuitka MMRE_macOS.py \
  --standalone --clang --lto=yes --jobs=10 \
  --macos-target-arch=arm64 --macos-create-app-bundle \
  --output-filename=MMRE_macOS \
  --enable-plugin=pyside6 \
  --include-package=cv2 \
  --include-package-data=mediapipe \
  --include-data-dir=/Users/<user>/studio1_exe/.venv/lib/python3.11/site-packages/mediapipe=mediapipe \
  --nofollow-import-to=gi,pygobject,gst \
  --noinclude-dlls="/opt/homebrew/opt/ffmpeg@*/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/Cellar/ffmpeg/*/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/opt/gstreamer/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/Cellar/gstreamer/*/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/opt/glib/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/Cellar/glib/*/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/opt/orc/lib/*.dylib" \
  --noinclude-dlls="/opt/homebrew/Cellar/orc/*/lib/*.dylib"

Nuitka-Plugins:pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6/qt-plugins'.
FATAL:     Error, problem with dependency scan of '~/studio1_exe/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so' with '/opt/homebrew/opt/gstreamer/lib/libgstbase-1.0.0.dylib' please report the bug.

## 📉 Expected Behavior

Nuitka should complete the build (standalone/app bundle), leaving GStreamer to be provided externally by Homebrew at runtime.

## 📄 Actual Behavior & Output

Build aborts with the FATAL shown above. It appears Nuitka’s dependency scanner still attempts to walk Homebrew’s libgst* dylibs referenced by cv2.abi3.so, even when they are excluded via --

## ↩️ Regression (if applicable)

Did this work in a previous version of Nuitka? If so, *please* specify the last known working
version. *(This helps dramatically in isolating the issue, e.g., via `git bisect`.)*

## 💡 Additional Context (Optional)

Workarounds tested:

If I rebuild OpenCV without GStreamer (e.g., WITH_FFMPEG=ON, WITH_GSTREAMER=OFF), the same Nuitka build works.

If I switch to PyInstaller onedir (leaving GStreamer external), the build works and the app runs via GStreamer at runtime.

Trying to route OpenCV GStreamer via plugin mode (not directly linked) is possible, but building that wheel on macOS through opencv-python scaffolding is finicky; disabling gapi was required to get past an unrelated CMake export-set issue.

GStreamer presence:

Homebrew gstreamer 1.26.5_5 with base/good/bad/libav installed.

cv2.getBuildInformation() shows GStreamer: YES, FFMPEG: NO.
______________________________________________________________________

## 🚫 Unwelcome Practices (Please Read)

- **No Screenshots of Text:** Do *not* post screenshots of code, errors, or console output unless
  absolutely necessary (e.g., a GUI display problem). Provide text directly so it's searchable and
  copyable. Reports without proper text are likely to be rejected.
- **Do Not Close Issues Yourself:** We will close issues once they are resolved in a stable release.
  If you find your issue is invalid, you may close it, and we will tag it as `invalid` or even
  delete it later.
- **Do Not Report Against `factory` Branch:** Unless specifically asked, avoid reporting issues
  found on the `factory` branch as it's often unstable. Discuss on Discord first.

______________________________________________________________________

## 💼 Commercial Support

Consider Nuitka commercial support for priority assistance, which also helps sustain Nuitka's
development. This allows for direct code sharing or paid time for issue resolution in your
environment.

______________________________________________________________________

**PLEASE REMOVE ALL TEMPLATE TEXT (INCLUDING THIS LINE) BEFORE SUBMITTING YOUR ISSUE.**

**Comment by kayhayen** [comment]
Yes, the dependency resolution is done first and only then it's deciding what of that it wants to include. It's a shame the Nuitka `--version` output didn't make this report, that has worked most often recently, why not now? Anyway, it seems you need to provide some sort of script to reproduce this. I don't really want to build cv2 manually just to attempt to find out if it reproduces anything.

**Comment by khayyat71** [comment]
# Repro steps (macOS arm64, Homebrew GStreamer)
# 0) Ensure Homebrew GStreamer (runtime)
brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav

# 1) Build OpenCV (cv2) linked to GStreamer (not plugin mode)
Make sure pkg-config sees Homebrew GStreamer
export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:/opt/homebrew/opt/gstreamer/lib/pkgconfig:/opt/homebrew/opt/gst-plugins-base/lib/pkgconfig:${PKG_CONFIG_PATH:-}"

# CMake flags for opencv-python build: GStreamer ON, FFmpeg OFF, plugin mode OFF
export CMAKE_ARGS="
  -DWITH_GSTREAMER=ON
  -DWITH_FFMPEG=OFF
  -DVIDEOIO_ENABLE_PLUGINS=OFF
  -DBUILD_TESTS=OFF
  -DBUILD_PERF_TESTS=OFF
  -DBUILD_EXAMPLES=OFF
  -DCMAKE_BUILD_TYPE=Release
  -DPython3_EXECUTABLE=$(python -c 'import sys; print(sys.executable)')
  -DPython3_NumPy_INCLUDE_DIRS=$(python -c 'import numpy as np; print(np.get_include())')
"

pip wheel . -v            # run in opencv-python repo root
pip install ./opencv_python-*.whl --force-reinstall


Verify cv2 links to libgst*:

otool -L $(python -c 'import cv2, pathlib; print(pathlib.Path(cv2.__file__))') | egrep 'libgstreamer|libgstbase' -i
Expect at least libgstbase-1.0.0.dylib

# 2) Minimal script (just import cv2)

sscce.py

import cv2
print("cv2 version:", cv2.__version__)

# 3) Compile with Nuitka (this triggers the crash)
python -m nuitka --standalone --macos-create-app-bundle sscce.py


# Observed error:

FATAL: Error, problem with dependency scan of '.../cv2.abi3.so'
with '/opt/homebrew/opt/gstreamer/lib/libgstbase-1.0.0.dylib' please report the bug.

**Comment by khayyat71** [comment]
BTW, opencv-python==4.11.0 (custom wheel built from the opencv-python repo)

**Comment by kayhayen** [comment]
I recently had an issue with "Standalone Build Python" where a DLL was excluded due to being outside, and then caused this crash. Looking at "/opt/homebrew/opt/gstreamer/lib" that is definitely outside of what's currently allowed, however, it would appear this is not happening:

```
    if isHomebrewPython():
        inside_paths.insert(0, getHomebrewInstallPath())
```

However, then in the actual macOS specific code, it adds this only for the directories to scan:

```
    if isHomebrewPython():
        result.append(os.path.join(getHomebrewInstallPath(), "lib"))
```

That then will prevent your gstreamer lib directory from being found. I just need to make it add all subdirectories as valid candidates to hold directories. I could limit it to ones named `lib` but then there would effectively still be a mismatch.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by khayyat71** [comment]
It's not working: FATAL: Error, problem with dependency scan of '/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so' with '/opt/homebrew/opt/gstreamer/lib/libgstbase-1.0.0.dylib' please report the bug.

**Comment by kayhayen** [comment]
Ah, the directory names are relative to the scanned one, so I need to join them still, sorry, going to improve that, please try again.

**Comment by khayyat71** [comment]
## Update: Tested with factory branch

Tested with Nuitka 2.8 from the `factory` branch (commit fd64297):
- Same FATAL error occurs
- Minimal reproduction: 
## Minimal Reproduction Code (sscce.py)
```python
import cv2
print("cv2 version:", cv2.__version__)
`python -m nuitka --standalone --macos-create-app-bundle sscce.py`
- Issue persists even with the simplest possible command line

**Comment by kayhayen** [comment]
Dang that's not good, I am going to look at what it does anyway quickly.

**Comment by kayhayen** [comment]
This is part of the stable release 4.0 that I just made.
